# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DockerAuth < Formula
  desc ""
  homepage "https://github.com/sgaunet/homebrew-tools"
  version "0.1.0-beta1"
  depends_on :linux

  on_intel do
    if Hardware::CPU.is_64_bit?
      url "https://github.com/sgaunet/docker-auth/releases/download/v0.1.0-beta1/docker-auth_0.1.0-beta1_linux_amd64"
      sha256 "7366a77c8c13c1b115804ed761c4e36d8cf29d904f147a3b2ba0ed429c2330dd"

      def install
        bin.install "docker-auth_0.1.0-beta1_linux_amd64" => "docker-auth"
      end
    end
  end
  on_arm do
    if !Hardware::CPU.is_64_bit?
      url "https://github.com/sgaunet/docker-auth/releases/download/v0.1.0-beta1/docker-auth_0.1.0-beta1_linux_armv6"
      sha256 "c7fcd40e641d072b586ec73a7120b8c4ab39c8c7015392dd223045ff14135e8f"

      def install
        bin.install "docker-auth_0.1.0-beta1_linux_armv6" => "docker-auth"
      end
    end
  end
  on_arm do
    if Hardware::CPU.is_64_bit?
      url "https://github.com/sgaunet/docker-auth/releases/download/v0.1.0-beta1/docker-auth_0.1.0-beta1_linux_arm64"
      sha256 "eb959b087308ae2a4341050eb85c692805eebc0c77264d8a8337ae9d6f53b7e2"

      def install
        bin.install "docker-auth_0.1.0-beta1_linux_arm64" => "docker-auth"
      end
    end
  end
end
