# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DockerAuth < Formula
  desc ""
  homepage "https://github.com/sgaunet/homebrew-tools"
  version "0.1.0"
  depends_on :linux

  on_intel do
    if Hardware::CPU.is_64_bit?
      url "https://github.com/sgaunet/docker-auth/releases/download/v0.1.0/docker-auth_0.1.0_linux_amd64"
      sha256 "5056546fb2c646373f4fb7362e715dcc1be4be78c804afabe7f5cb18c4322408"

      def install
        bin.install "docker-auth_0.1.0_linux_amd64" => "docker-auth"
      end
    end
  end
  on_arm do
    if !Hardware::CPU.is_64_bit?
      url "https://github.com/sgaunet/docker-auth/releases/download/v0.1.0/docker-auth_0.1.0_linux_armv6"
      sha256 "447d126f7c43dbafd7dbfdc7681b1bb6441a0b24e5a3dc40d7307e6349583841"

      def install
        bin.install "docker-auth_0.1.0_linux_armv6" => "docker-auth"
      end
    end
  end
  on_arm do
    if Hardware::CPU.is_64_bit?
      url "https://github.com/sgaunet/docker-auth/releases/download/v0.1.0/docker-auth_0.1.0_linux_arm64"
      sha256 "ddd415193f0222fe4aade4ed44bb22128bd3a5efd57cb00fa13588fb4a26c413"

      def install
        bin.install "docker-auth_0.1.0_linux_arm64" => "docker-auth"
      end
    end
  end
end
