# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitlabBackup < Formula
  desc ""
  homepage "https://github.com/sgaunet/homebrew-tools"
  version "1.5.0"

  on_macos do
    on_intel do
      url "https://github.com/sgaunet/gitlab-backup/releases/download/v1.5.0/gitlab-backup_1.5.0_darwin_amd64"
      sha256 "7a30c8c9a9acf17a2c3f492625512dba77678ae84628f07a6d699de44e534e12"

      def install
        bin.install "gitlab-backup_1.5.0_darwin_amd64" => "gitlab-backup"
      end
    end
    on_arm do
      url "https://github.com/sgaunet/gitlab-backup/releases/download/v1.5.0/gitlab-backup_1.5.0_darwin_arm64"
      sha256 "fd6021c1ea18056e954cd1782320698f85a0cc9d270fd90a610786aee5cf83f2"

      def install
        bin.install "gitlab-backup_1.5.0_darwin_arm64" => "gitlab-backup"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sgaunet/gitlab-backup/releases/download/v1.5.0/gitlab-backup_1.5.0_linux_amd64"
        sha256 "442224392e12815e54b5cd6f7cf6030769568ccc59d28a33dc2f8be61c194840"

        def install
          bin.install "gitlab-backup_1.5.0_linux_amd64" => "gitlab-backup"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/sgaunet/gitlab-backup/releases/download/v1.5.0/gitlab-backup_1.5.0_linux_armv6"
        sha256 "d3fcdec1f233def7bac4c04c90a9bc08b0c4a138eddc5c1d1283dff04afa3f27"

        def install
          bin.install "gitlab-backup_1.5.0_linux_armv6" => "gitlab-backup"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sgaunet/gitlab-backup/releases/download/v1.5.0/gitlab-backup_1.5.0_linux_arm64"
        sha256 "8904acb81c28bdd4f023abc4571066ba7516ef000e9aef7d535f42f6dd154360"

        def install
          bin.install "gitlab-backup_1.5.0_linux_arm64" => "gitlab-backup"
        end
      end
    end
  end
end
