# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitlabBackup < Formula
  desc ""
  homepage "https://github.com/sgaunet/homebrew-tools"
  version "1.4.1"

  on_macos do
    on_intel do
      url "https://github.com/sgaunet/gitlab-backup/releases/download/v1.4.1/gitlab-backup_1.4.1_darwin_amd64"
      sha256 "3ba488d599f73a8561b86e5c3b93e3683c71166a327d1363cdbb8ab8afaf3825"

      def install
        bin.install "gitlab-backup_1.4.1_darwin_amd64" => "gitlab-backup"
      end
    end
    on_arm do
      url "https://github.com/sgaunet/gitlab-backup/releases/download/v1.4.1/gitlab-backup_1.4.1_darwin_arm64"
      sha256 "ee164b39c9be1db29d321593bc79753cd4fe16e7f0c23d00ac586fe30e0b74f0"

      def install
        bin.install "gitlab-backup_1.4.1_darwin_arm64" => "gitlab-backup"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sgaunet/gitlab-backup/releases/download/v1.4.1/gitlab-backup_1.4.1_linux_amd64"
        sha256 "ea3dbba4e6c8048bc5e425ee4f056d1027ef93e41d7905059fb78354d639e757"

        def install
          bin.install "gitlab-backup_1.4.1_linux_amd64" => "gitlab-backup"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/sgaunet/gitlab-backup/releases/download/v1.4.1/gitlab-backup_1.4.1_linux_armv6"
        sha256 "fa346cff804ac35569ba3cc09fa979fe69e7a82ead8ada366987df1758d21d8d"

        def install
          bin.install "gitlab-backup_1.4.1_linux_armv6" => "gitlab-backup"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sgaunet/gitlab-backup/releases/download/v1.4.1/gitlab-backup_1.4.1_linux_arm64"
        sha256 "8f6a19b38d93a4f51913c8c335725a08659911759e06629f65b8d4d9c3d71234"

        def install
          bin.install "gitlab-backup_1.4.1_linux_arm64" => "gitlab-backup"
        end
      end
    end
  end
end
