# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitlabTokenExpiration < Formula
  desc ""
  homepage "https://github.com/sgaunet/homebrew-tools"
  version "0.1.0-beta3"

  on_macos do
    on_intel do
      url "https://github.com/sgaunet/gitlab-token-expiration/releases/download/0.1.0-beta3/gitlab-token-expiration_0.1.0-beta3_darwin_amd64"
      sha256 "41d9e9c008cbac067b1d3c9ffc99d4d4915c1e56dfe299bd96c3877e42fb41e5"

      def install
        bin.install "gitlab-token-expiration_0.1.0-beta3_darwin_amd64" => "gitlab-token-expiration"
      end
    end
    on_arm do
      url "https://github.com/sgaunet/gitlab-token-expiration/releases/download/0.1.0-beta3/gitlab-token-expiration_0.1.0-beta3_darwin_arm64"
      sha256 "23f02cafc3d6eaae1fa467de224e726801167fce57f308f81da8fd89372bdc2f"

      def install
        bin.install "gitlab-token-expiration_0.1.0-beta3_darwin_arm64" => "gitlab-token-expiration"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sgaunet/gitlab-token-expiration/releases/download/0.1.0-beta3/gitlab-token-expiration_0.1.0-beta3_linux_amd64"
        sha256 "fe0dbf3f30aab3a4c10762f1dd5ce241d5a3e7a713938070b9099333ec62b666"

        def install
          bin.install "gitlab-token-expiration_0.1.0-beta3_linux_amd64" => "gitlab-token-expiration"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/sgaunet/gitlab-token-expiration/releases/download/0.1.0-beta3/gitlab-token-expiration_0.1.0-beta3_linux_armv6"
        sha256 "a298d348f897b26af61d68ebeadb3b134394430e8b0781f7d2f2bab48ac00ad2"

        def install
          bin.install "gitlab-token-expiration_0.1.0-beta3_linux_armv6" => "gitlab-token-expiration"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sgaunet/gitlab-token-expiration/releases/download/0.1.0-beta3/gitlab-token-expiration_0.1.0-beta3_linux_arm64"
        sha256 "082bb6beecba5f764c79a08b413592e3eedae411d302447fee0ed06d86800d63"

        def install
          bin.install "gitlab-token-expiration_0.1.0-beta3_linux_arm64" => "gitlab-token-expiration"
        end
      end
    end
  end
end
