# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitlabTokenExpiration < Formula
  desc ""
  homepage "https://github.com/sgaunet/homebrew-tools"
  version "0.1.0-beta1"

  on_macos do
    on_intel do
      url "https://github.com/sgaunet/gitlab-token-expiration/releases/download/0.1.0-beta1/gitlab-token-expiration_0.1.0-beta1_darwin_amd64"
      sha256 "55dbf13eb2525452d57ea378bedba4e7fe5b55f7926e295e687e22f37e5619db"

      def install
        bin.install "gitlab-token-expiration_0.1.0-beta1_darwin_amd64" => "gitlab-token-expiration"
      end
    end
    on_arm do
      url "https://github.com/sgaunet/gitlab-token-expiration/releases/download/0.1.0-beta1/gitlab-token-expiration_0.1.0-beta1_darwin_arm64"
      sha256 "92f5c254e367e74c23dfa637e322dc0983313c673ffded96573baee9a4125df4"

      def install
        bin.install "gitlab-token-expiration_0.1.0-beta1_darwin_arm64" => "gitlab-token-expiration"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sgaunet/gitlab-token-expiration/releases/download/0.1.0-beta1/gitlab-token-expiration_0.1.0-beta1_linux_amd64"
        sha256 "c5c8120c8121fdb8f56a9ca984cb2101af4b659b8ae43dfd187d498477dc1f13"

        def install
          bin.install "gitlab-token-expiration_0.1.0-beta1_linux_amd64" => "gitlab-token-expiration"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/sgaunet/gitlab-token-expiration/releases/download/0.1.0-beta1/gitlab-token-expiration_0.1.0-beta1_linux_armv6"
        sha256 "0c118f7cd214da2ece8899c390f8d8d5aa222386518aae178fed5e987f2ccb48"

        def install
          bin.install "gitlab-token-expiration_0.1.0-beta1_linux_armv6" => "gitlab-token-expiration"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sgaunet/gitlab-token-expiration/releases/download/0.1.0-beta1/gitlab-token-expiration_0.1.0-beta1_linux_arm64"
        sha256 "378d57d76e8bd5899272d997d46848d03e3d23172434a6faec6ad2c84464bcc1"

        def install
          bin.install "gitlab-token-expiration_0.1.0-beta1_linux_arm64" => "gitlab-token-expiration"
        end
      end
    end
  end
end
