# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitlabBackup < Formula
  desc ""
  homepage "https://github.com/sgaunet/homebrew-tools"
  version "1.6.0"

  on_macos do
    on_intel do
      url "https://github.com/sgaunet/gitlab-backup/releases/download/v1.6.0/gitlab-backup_1.6.0_darwin_amd64"
      sha256 "a5d4ad7eb335c4a178864384ec726e4074e0dcf1b362b2bb04c060bbaf779ea2"

      def install
        bin.install "gitlab-backup_1.6.0_darwin_amd64" => "gitlab-backup"
      end
    end
    on_arm do
      url "https://github.com/sgaunet/gitlab-backup/releases/download/v1.6.0/gitlab-backup_1.6.0_darwin_arm64"
      sha256 "54d8619a2747f45ea9b0900bdc5be926fc6687c6314cada35827f79cd5266b53"

      def install
        bin.install "gitlab-backup_1.6.0_darwin_arm64" => "gitlab-backup"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sgaunet/gitlab-backup/releases/download/v1.6.0/gitlab-backup_1.6.0_linux_amd64"
        sha256 "a5bc71601af8fa7dca14e07e30c927e5355d002f7dfc81932e44331dfd8988bb"

        def install
          bin.install "gitlab-backup_1.6.0_linux_amd64" => "gitlab-backup"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/sgaunet/gitlab-backup/releases/download/v1.6.0/gitlab-backup_1.6.0_linux_armv6"
        sha256 "3fbc06217ee186580a7bc546f17ccdcd65d419004457bd67b640b1612cbf38f2"

        def install
          bin.install "gitlab-backup_1.6.0_linux_armv6" => "gitlab-backup"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sgaunet/gitlab-backup/releases/download/v1.6.0/gitlab-backup_1.6.0_linux_arm64"
        sha256 "c5726ab8080fdfbca9185e247c8b8912c3581b98012c6b345de2df0ed95a1a73"

        def install
          bin.install "gitlab-backup_1.6.0_linux_arm64" => "gitlab-backup"
        end
      end
    end
  end
end
