# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class JwtCli < Formula
  desc ""
  homepage "https://github.com/sgaunet/homebrew-tools"
  version "1.2.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sgaunet/jwt-cli/releases/download/v1.2.1/jwt-cli_1.2.1_darwin_amd64"
      sha256 "d9fcf6348141324b0f58971638c0ea6a9e3d3b1869a40385748b464d7098dd7f"

      def install
        bin.install "jwt-cli_1.2.1_darwin_amd64" => "jwt-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sgaunet/jwt-cli/releases/download/v1.2.1/jwt-cli_1.2.1_darwin_arm64"
      sha256 "b7cd6275fca0c1d4fb7d0cdacf8f2290d10e86ad33c8dc70d2c16076f4450c89"

      def install
        bin.install "jwt-cli_1.2.1_darwin_arm64" => "jwt-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sgaunet/jwt-cli/releases/download/v1.2.1/jwt-cli_1.2.1_linux_amd64"
        sha256 "a90107c787a4de1cebbfdd5be8c7c216b375843278aa5e0b28b75c2e4ccb29c1"

        def install
          bin.install "jwt-cli_1.2.1_linux_amd64" => "jwt-cli"
        end
      end
    end
    if Hardware::CPU.arm?
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/sgaunet/jwt-cli/releases/download/v1.2.1/jwt-cli_1.2.1_linux_armv6"
        sha256 "cc967d87f95f28fa64a0e82dbf4744e199e69131afb1ec4f80c1099ace49746b"

        def install
          bin.install "jwt-cli_1.2.1_linux_armv6" => "jwt-cli"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sgaunet/jwt-cli/releases/download/v1.2.1/jwt-cli_1.2.1_linux_arm64"
        sha256 "5d55c51b295d385a6f61c65c48b57a738f2306a2e91227549e1d8e4ce3a14459"

        def install
          bin.install "jwt-cli_1.2.1_linux_arm64" => "jwt-cli"
        end
      end
    end
  end
end
