# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mdtohtml < Formula
  desc ""
  homepage "https://github.com/sgaunet/homebrew-tools"
  version "0.6.5"

  on_macos do
    on_intel do
      url "https://github.com/sgaunet/mdtohtml/releases/download/v0.6.5/mdtohtml_0.6.5_darwin_amd64"
      sha256 "c465676fb04775df07d204962fc0e8a017a1a2b4af16606c10ca5788a422ea5d"

      def install
        bin.install "mdtohtml_0.6.5_darwin_amd64" => "mdtohtml"
      end
    end
    on_arm do
      url "https://github.com/sgaunet/mdtohtml/releases/download/v0.6.5/mdtohtml_0.6.5_darwin_arm64"
      sha256 "19c269adb382cddf2cb501b40ee07fcd7b1722ba228725a1b5e9022332055f27"

      def install
        bin.install "mdtohtml_0.6.5_darwin_arm64" => "mdtohtml"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sgaunet/mdtohtml/releases/download/v0.6.5/mdtohtml_0.6.5_linux_amd64"
        sha256 "55075fc5ae8f685949cfed95542826a60069f9574c27fded798ef9de164214c3"

        def install
          bin.install "mdtohtml_0.6.5_linux_amd64" => "mdtohtml"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/sgaunet/mdtohtml/releases/download/v0.6.5/mdtohtml_0.6.5_linux_armv6"
        sha256 "a1e19226823d7cf97ec5177b344c1c831f0028eb8a347e14ed761d67d13a2b7d"

        def install
          bin.install "mdtohtml_0.6.5_linux_armv6" => "mdtohtml"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sgaunet/mdtohtml/releases/download/v0.6.5/mdtohtml_0.6.5_linux_arm64"
        sha256 "3c3c69b148d2242eb35acdd1c9abda4fc82b15e431d4cf53eb40b7f72ca67713"

        def install
          bin.install "mdtohtml_0.6.5_linux_arm64" => "mdtohtml"
        end
      end
    end
  end
end
