# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pplx < Formula
  desc ""
  homepage "https://github.com/sgaunet/homebrew-tools"
  version "0.1.0"

  on_macos do
    on_intel do
      url "https://github.com/sgaunet/pplx/releases/download/v0.1.0/pplx_0.1.0_darwin_amd64"
      sha256 "e4e093d3c40880ff4ed10e5b23645adcff1252150e6a1ebd00b6084262f09bdb"

      def install
        bin.install "pplx_0.1.0_darwin_amd64" => "pplx"
      end
    end
    on_arm do
      url "https://github.com/sgaunet/pplx/releases/download/v0.1.0/pplx_0.1.0_darwin_arm64"
      sha256 "3cda0b6d97ad1d724f06e59e67d2d1fec284154154f6c0aad4dca5f899f6e63d"

      def install
        bin.install "pplx_0.1.0_darwin_arm64" => "pplx"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sgaunet/pplx/releases/download/v0.1.0/pplx_0.1.0_linux_amd64"
        sha256 "218236618c723400a3549c9f3c0ae89aa1b66ea90204a7689d2d6d4e61a8d548"

        def install
          bin.install "pplx_0.1.0_linux_amd64" => "pplx"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/sgaunet/pplx/releases/download/v0.1.0/pplx_0.1.0_linux_armv6"
        sha256 "7730f5c147e46fb5f221dcf68b21b7f58583ebf275f0abeb9766c45c96f2f9ff"

        def install
          bin.install "pplx_0.1.0_linux_armv6" => "pplx"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sgaunet/pplx/releases/download/v0.1.0/pplx_0.1.0_linux_arm64"
        sha256 "2d841549d45265553bf379f7cc313629ce28914a93ad1fcb3854304edef900a9"

        def install
          bin.install "pplx_0.1.0_linux_arm64" => "pplx"
        end
      end
    end
  end
end
