# This file was generated by GoReleaser. DO NOT EDIT.
cask "askit" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "76fb62759adf2968265e8f58ad4b9b11e579fdabd8b3c5b997ac5f824186763f"
      url "https://github.com/sgaunet/askit/releases/download/v#{version}/askit_#{version}_darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "fdd9467fa90fe45c57ceab4d2ebc9e8343eeafe67fb32bcb3fa01e61cc1c37af"
      url "https://github.com/sgaunet/askit/releases/download/v#{version}/askit_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ede4518745ed652b173505316c503240adcaaf515b48a3f6e875add1c5e2d12f"
      url "https://github.com/sgaunet/askit/releases/download/v#{version}/askit_#{version}_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "ed1527d9ef069bc4ac7201d30b06576a6add73085ed615f4e0fb187ff44e80f3"
      url "https://github.com/sgaunet/askit/releases/download/v#{version}/askit_#{version}_linux_arm64.tar.gz"
    end
  end

  name "askit"
  desc "Terminal client for OpenAI-compatible chat completion APIs with @path file references and named presets"
  homepage "https://github.com/sgaunet/askit"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "askit"

  # No zap stanza required

end
