# This file was generated by GoReleaser. DO NOT EDIT.
cask "askit" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "fb4ee7e3e5b040fc1ae32a1fc0b996bb1925f1e70f4130f0321d774fb6f4dad9"
      url "https://github.com/sgaunet/askit/releases/download/v#{version}/askit_#{version}_darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "f9d734996a7fe907f22b93654cd931250898213db33697360f67dff1bf09fedf"
      url "https://github.com/sgaunet/askit/releases/download/v#{version}/askit_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e9374a1a393c8779665e82e61b24631ae8df3e893bde59d96eb75cef4bdedde5"
      url "https://github.com/sgaunet/askit/releases/download/v#{version}/askit_#{version}_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "964382caa2af70f4f81ebfc4b5fae1baf9dbc1e4b256e467df448c846b03297e"
      url "https://github.com/sgaunet/askit/releases/download/v#{version}/askit_#{version}_linux_arm64.tar.gz"
    end
  end

  name "askit"
  desc "Terminal client for OpenAI-compatible chat completion APIs with @path file references and named presets"
  homepage "https://github.com/sgaunet/askit"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "askit"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/askit"]
    end
  end

  # No zap stanza required

end
