# This file was generated by GoReleaser. DO NOT EDIT.
cask "askit" do
  version "0.2.1"

  on_macos do
    on_intel do
      sha256 "748c244d5bafad8cd14a7eace529c80fc7d23688621beaf51afc02f691a2e012"
      url "https://github.com/sgaunet/askit/releases/download/v#{version}/askit_#{version}_darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "6dfaefbedb591f2dcdb012401d12cac017615f54bfd016713fd7abd0a006670e"
      url "https://github.com/sgaunet/askit/releases/download/v#{version}/askit_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "8baa911add6755c22b7021aefb9bc255df0f42f9da86bf8624f77da6140f73d7"
      url "https://github.com/sgaunet/askit/releases/download/v#{version}/askit_#{version}_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "88594600753ff403caa20b6cc7b50980988089d3f296ffa9b0c6f5f9a1ae2390"
      url "https://github.com/sgaunet/askit/releases/download/v#{version}/askit_#{version}_linux_arm64.tar.gz"
    end
  end

  name "askit"
  desc "Terminal client for OpenAI-compatible chat completion APIs with @path file references and named presets"
  homepage "https://github.com/sgaunet/askit"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "askit"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/askit"]
    end
  end

  # No zap stanza required

end
