# This file was generated by GoReleaser. DO NOT EDIT.
cask "auto-mr" do
  version "0.16.1"

  on_macos do
    on_intel do
      sha256 "756d5f35add073565b1f984331c91b1342aefa92b962a308d782ad1129ba3f8d"
      url "https://github.com/sgaunet/auto-mr/releases/download/v#{version}/auto-mr_#{version}_darwin_amd64"
      binary "auto-mr_0.16.1_darwin_amd64", target: "auto-mr"
    end
    on_arm do
      sha256 "d619b9f61f9d4f4a4f11a99fbae6e24d099858c22c6f48a9c87501728557b21b"
      url "https://github.com/sgaunet/auto-mr/releases/download/v#{version}/auto-mr_#{version}_darwin_arm64"
      binary "auto-mr_0.16.1_darwin_arm64", target: "auto-mr"
    end
  end

  on_linux do
    on_intel do
      sha256 "935ef2597271410a233fe4e030488ea39b8e4799bd8c81eaa1623f6854a4eb38"
      url "https://github.com/sgaunet/auto-mr/releases/download/v#{version}/auto-mr_#{version}_linux_amd64"
      binary "auto-mr_0.16.1_linux_amd64", target: "auto-mr"
    end
    on_arm do
      sha256 "e6e9c7d85a51af9e5535c3981715d0c614ba6abaf4ef023dbb457df494339274"
      url "https://github.com/sgaunet/auto-mr/releases/download/v#{version}/auto-mr_#{version}_linux_arm64"
      binary "auto-mr_0.16.1_linux_arm64", target: "auto-mr"
    end
  end

  name "auto-mr"
  desc "Automated merge requests for GitLab, GitHub and self-hosted Forgejo"
  homepage "https://github.com/sgaunet/auto-mr"

  livecheck do
    skip "Auto-generated on release."
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}"]
    end
  end

  # No zap stanza required

end
