# This file was generated by GoReleaser. DO NOT EDIT.
cask "calcdate" do
  version "2.1.2"

  on_macos do
    on_intel do
      sha256 "66ec2a6c876f1192a6c7a543d691307078364e77a86775b28065ff8fe4b68f8c"
      url "https://github.com/sgaunet/calcdate/releases/download/v#{version}/calcdate_#{version}_darwin_amd64"
      binary "calcdate_2.1.2_darwin_amd64", target: "calcdate"
    end
    on_arm do
      sha256 "afd63211c8efdada1f4170453f745ed55635002759494c17921bf8d08e587424"
      url "https://github.com/sgaunet/calcdate/releases/download/v#{version}/calcdate_#{version}_darwin_arm64"
      binary "calcdate_2.1.2_darwin_arm64", target: "calcdate"
    end
  end

  on_linux do
    on_intel do
      sha256 "c718f44dc56422d63aaeb6a799676d1755f80376956e30e1f60b1aaae1b34067"
      url "https://github.com/sgaunet/calcdate/releases/download/v#{version}/calcdate_#{version}_linux_amd64"
      binary "calcdate_2.1.2_linux_amd64", target: "calcdate"
    end
    on_arm do
      sha256 "305033e967f7b873d00de79832ff655058ad977471631b5d108502fb68aec8fd"
      url "https://github.com/sgaunet/calcdate/releases/download/v#{version}/calcdate_#{version}_linux_arm64"
      binary "calcdate_2.1.2_linux_arm64", target: "calcdate"
    end
  end

  name "calcdate"
  desc "Command-line utility for date calculations with intuitive expression syntax"
  homepage "https://github.com/sgaunet/calcdate"

  livecheck do
    skip "Auto-generated on release."
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}"]
    end
  end

  # No zap stanza required

end
