# This file was generated by GoReleaser. DO NOT EDIT.
cask "dsn" do
  version "3.3.3"

  on_macos do
    on_intel do
      sha256 "ae3d463e722ab11a3d7b16a9b3ce4dbc4f9728d05f92c0d31c8d0c35ad05cb03"
      url "https://github.com/sgaunet/dsn/releases/download/v#{version}/dsn_#{version}_darwin_amd64"
      binary "dsn_3.3.3_darwin_amd64", target: "dsn"
    end
    on_arm do
      sha256 "40393cc8e01260f178de4aa3abed6544256cc5f40851e8e83226f92604bcbaf6"
      url "https://github.com/sgaunet/dsn/releases/download/v#{version}/dsn_#{version}_darwin_arm64"
      binary "dsn_3.3.3_darwin_arm64", target: "dsn"
    end
  end

  on_linux do
    on_intel do
      sha256 "92e18a617c95a349f9d3c1b96d053456b0568def4b00dc84be48c04366de6b1d"
      url "https://github.com/sgaunet/dsn/releases/download/v#{version}/dsn_#{version}_linux_amd64"
      binary "dsn_3.3.3_linux_amd64", target: "dsn"
    end
    on_arm do
      sha256 "7ed5871a0ac7719efe53cc4d8c401101cedc5fef6b3ee38b3355a3d396e006a3"
      url "https://github.com/sgaunet/dsn/releases/download/v#{version}/dsn_#{version}_linux_arm64"
      binary "dsn_3.3.3_linux_arm64", target: "dsn"
    end
  end

  name "dsn"
  desc "Handle data source names like scheme://user:password@host:port/dbname"
  homepage "https://github.com/sgaunet/dsn"

  livecheck do
    skip "Auto-generated on release."
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}"]
    end
  end

  # No zap stanza required

end
