# This file was generated by GoReleaser. DO NOT EDIT.
cask "gini" do
  version "0.6.1"

  on_macos do
    on_intel do
      sha256 "273b55fd46f68564990f98744dfcc1bcd7bb6b6e4c38cb580381261341ff17a2"
      url "https://github.com/sgaunet/gini/releases/download/v#{version}/gini_#{version}_darwin_amd64"
      binary "gini_0.6.1_darwin_amd64", target: "gini"
    end
    on_arm do
      sha256 "6487c60f12a1dbae3730864228affadf2768506ff5d190a6f5f074ea6674d375"
      url "https://github.com/sgaunet/gini/releases/download/v#{version}/gini_#{version}_darwin_arm64"
      binary "gini_0.6.1_darwin_arm64", target: "gini"
    end
  end

  on_linux do
    on_intel do
      sha256 "53fbdb9b1c7b5e9904a03e41719ad6fa6921fb1ba22ca879c04d9aa20cdb292b"
      url "https://github.com/sgaunet/gini/releases/download/v#{version}/gini_#{version}_linux_amd64"
      binary "gini_0.6.1_linux_amd64", target: "gini"
    end
    on_arm do
      sha256 "1890ffee1af53325111bd604086ad3fbdd6a36f32bfeb4fbb98800213be423e1"
      url "https://github.com/sgaunet/gini/releases/download/v#{version}/gini_#{version}_linux_arm64"
      binary "gini_0.6.1_linux_arm64", target: "gini"
    end
  end

  name "gini"
  desc "Basic read and write operations on INI files"
  homepage "https://github.com/sgaunet/gini"

  livecheck do
    skip "Auto-generated on release."
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}"]
    end
  end

  # No zap stanza required

end
