# This file was generated by GoReleaser. DO NOT EDIT.
cask "gitcommit" do
  version "0.1.2"

  on_macos do
    on_intel do
      sha256 "26af8bb9b29f0d2579e9cfc28977d779d7b684014853cbc89642e9e413b5f2de"
      url "https://github.com/sgaunet/gitcommit/releases/download/v#{version}/gitcommit_#{version}_darwin_amd64"
      binary "gitcommit_0.1.2_darwin_amd64", target: "gitcommit"
    end
    on_arm do
      sha256 "e4c6f39533b26eef316ecff09654fff7a548a34b5241962d7d7ea37091309e37"
      url "https://github.com/sgaunet/gitcommit/releases/download/v#{version}/gitcommit_#{version}_darwin_arm64"
      binary "gitcommit_0.1.2_darwin_arm64", target: "gitcommit"
    end
  end

  on_linux do
    on_intel do
      sha256 "4bc2de5f3abffe68e88896041ec7d71f421df44084421125aeaa6f229e2c055c"
      url "https://github.com/sgaunet/gitcommit/releases/download/v#{version}/gitcommit_#{version}_linux_amd64"
      binary "gitcommit_0.1.2_linux_amd64", target: "gitcommit"
    end
    on_arm do
      sha256 "5600e734a40edd64d5808f41a095cc8fce712e40f0d47bf4295e978833dcf35c"
      url "https://github.com/sgaunet/gitcommit/releases/download/v#{version}/gitcommit_#{version}_linux_arm64"
      binary "gitcommit_0.1.2_linux_arm64", target: "gitcommit"
    end
  end

  name "gitcommit"
  desc "Create git commits with specific historical dates"
  homepage "https://github.com/sgaunet/gitcommit"

  livecheck do
    skip "Auto-generated on release."
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}"]
    end
  end

  # No zap stanza required

end
