# This file was generated by GoReleaser. DO NOT EDIT.
cask "gitlab-token-expiration" do
  version "0.4.2"

  on_macos do
    on_intel do
      sha256 "e2837c9f5a8259d2b80918326fff319b1aa672ca95751c905cefdea0e07261f6"
      url "https://github.com/sgaunet/gitlab-token-expiration/releases/download/v#{version}/gitlab-token-expiration_#{version}_darwin_amd64"
      binary "gitlab-token-expiration_0.4.2_darwin_amd64", target: "gitlab-token-expiration"
    end
    on_arm do
      sha256 "4b91471424744892892bb3d87fb24c36c9aca6fd6bd5c24b423e8c2e1f091512"
      url "https://github.com/sgaunet/gitlab-token-expiration/releases/download/v#{version}/gitlab-token-expiration_#{version}_darwin_arm64"
      binary "gitlab-token-expiration_0.4.2_darwin_arm64", target: "gitlab-token-expiration"
    end
  end

  on_linux do
    on_intel do
      sha256 "79c3dfc4f53887d77de6363284458e0b58b9e2ddffcaf794abe1698b1c008e09"
      url "https://github.com/sgaunet/gitlab-token-expiration/releases/download/v#{version}/gitlab-token-expiration_#{version}_linux_amd64"
      binary "gitlab-token-expiration_0.4.2_linux_amd64", target: "gitlab-token-expiration"
    end
    on_arm do
      sha256 "c97045ac12f81713bc282050e94e314ede69864bde06ec9e302bc0886ef4777e"
      url "https://github.com/sgaunet/gitlab-token-expiration/releases/download/v#{version}/gitlab-token-expiration_#{version}_linux_arm64"
      binary "gitlab-token-expiration_0.4.2_linux_arm64", target: "gitlab-token-expiration"
    end
  end

  name "gitlab-token-expiration"
  desc "List expiration dates of GitLab project, group and personal access tokens"
  homepage "https://github.com/sgaunet/gitlab-token-expiration"

  livecheck do
    skip "Auto-generated on release."
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}"]
    end
  end

  # No zap stanza required

end
