# This file was generated by GoReleaser. DO NOT EDIT.
cask "gitlab-mcp" do
  version "0.13.1"

  on_macos do
    on_intel do
      sha256 "8fb9eec72b77c7addbc9554e8b0988ed7601e381d94996307b4664986da03c16"
      url "https://github.com/sgaunet/gitlab-mcp/releases/download/v#{version}/gitlab-mcp_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "dbdfe96bad41bd2ad9d6700688bba938b1c1d585be37a9aac1273a6151acb1dd"
      url "https://github.com/sgaunet/gitlab-mcp/releases/download/v#{version}/gitlab-mcp_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "559fe337a3c1af0970790c54f57ed9893eaae361c02f9a7dc8122a00de6e0179"
      url "https://github.com/sgaunet/gitlab-mcp/releases/download/v#{version}/gitlab-mcp_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "2868e8c01d7b5349176b0f22b640de64a5f0f010f8a70e2df6eaf090a82412da"
      url "https://github.com/sgaunet/gitlab-mcp/releases/download/v#{version}/gitlab-mcp_#{version}_linux_arm64.tar.gz"
    end
  end

  name "gitlab-mcp"
  desc "Model Context Protocol server with GitLab integration tools for Claude Code"
  homepage "https://github.com/sgaunet/gitlab-mcp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gitlab-mcp"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}"]
    end
  end

  # No zap stanza required

end
