# This file was generated by GoReleaser. DO NOT EDIT.
cask "gitlab-backup" do
  version "1.18.2"

  on_macos do
    on_intel do
      sha256 "25d8549a99ad17b533f659af491864f218c5ee066ce3f5a8131794b027fc8fc2"
      url "https://github.com/sgaunet/gitlab-backup/releases/download/v#{version}/gitlab-backup_#{version}_darwin_amd64"
      binary "gitlab-backup_1.18.2_darwin_amd64", target: "gitlab-backup"
    end
    on_arm do
      sha256 "3d52f8ec3b6e7eb3c2fba9c89316db3c7c9fca330e46c97d15518d7a42f359d9"
      url "https://github.com/sgaunet/gitlab-backup/releases/download/v#{version}/gitlab-backup_#{version}_darwin_arm64"
      binary "gitlab-backup_1.18.2_darwin_arm64", target: "gitlab-backup"
    end
  end

  on_linux do
    on_intel do
      sha256 "f5077864e983ee51d269b47518709dbbb236a0c86bc55698768c3955626fbd1f"
      url "https://github.com/sgaunet/gitlab-backup/releases/download/v#{version}/gitlab-backup_#{version}_linux_amd64"
      binary "gitlab-backup_1.18.2_linux_amd64", target: "gitlab-backup"
    end
    on_arm do
      sha256 "b49091c6b9c191dda1e4aa863762b3c135484742729c2a3e866fa3ebccf6d796"
      url "https://github.com/sgaunet/gitlab-backup/releases/download/v#{version}/gitlab-backup_#{version}_linux_arm64"
      binary "gitlab-backup_1.18.2_linux_arm64", target: "gitlab-backup"
    end
  end

  name "gitlab-backup"
  desc "A tool for backing up GitLab projects"
  homepage "https://github.com/sgaunet/gitlab-backup"

  livecheck do
    skip "Auto-generated on release."
  end

  # No zap stanza required

end
