# This file was generated by GoReleaser. DO NOT EDIT.
cask "gitlab-restore" do
  version "1.20.1"

  on_macos do
    on_intel do
      sha256 "4f5221564bd9b2a4d75d78c75cf2857346f1664a3596739e38f84e350dd81b4b"
      url "https://github.com/sgaunet/gitlab-backup/releases/download/v#{version}/gitlab-restore_#{version}_darwin_amd64"
      binary "gitlab-restore_1.20.1_darwin_amd64", target: "gitlab-restore"
    end
    on_arm do
      sha256 "04a726f6e6ff63c715389398d10628466162528b2b8fe07eece3fac721de489f"
      url "https://github.com/sgaunet/gitlab-backup/releases/download/v#{version}/gitlab-restore_#{version}_darwin_arm64"
      binary "gitlab-restore_1.20.1_darwin_arm64", target: "gitlab-restore"
    end
  end

  on_linux do
    on_intel do
      sha256 "8deddad2f2125f0d87aae31af1534b6e19cc725b9785fac163519f8df9067d1c"
      url "https://github.com/sgaunet/gitlab-backup/releases/download/v#{version}/gitlab-restore_#{version}_linux_amd64"
      binary "gitlab-restore_1.20.1_linux_amd64", target: "gitlab-restore"
    end
    on_arm do
      sha256 "ee7022b2f73f8801431671984345febfec94de0aa5c45d140dbb262f7d50f40b"
      url "https://github.com/sgaunet/gitlab-backup/releases/download/v#{version}/gitlab-restore_#{version}_linux_arm64"
      binary "gitlab-restore_1.20.1_linux_arm64", target: "gitlab-restore"
    end
  end

  name "gitlab-restore"
  desc "A tool for restoring GitLab projects from backups"
  homepage "https://github.com/sgaunet/gitlab-backup"

  livecheck do
    skip "Auto-generated on release."
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}"]
    end
  end

  # No zap stanza required

end
