# This file was generated by GoReleaser. DO NOT EDIT.
cask "gitlab-backup" do
  name "gitlab-backup"
  desc "A tool for backing up GitLab projects"
  homepage "https://github.com/sgaunet/gitlab-backup"
  version "1.16.0"

  livecheck do
    skip "Auto-generated on release."
  end

  on_macos do
    on_intel do
      url "https://github.com/sgaunet/gitlab-backup/releases/download/v#{version}/gitlab-backup_#{version}_darwin_amd64"
      sha256 "60611a28fd267e85117e1ec326518e1d9ecd0e67d0867381269d5dc4fb54e12a"
      binary "gitlab-backup_1.16.0_darwin_amd64", target: "gitlab-backup"
    end
    on_arm do
      url "https://github.com/sgaunet/gitlab-backup/releases/download/v#{version}/gitlab-backup_#{version}_darwin_arm64"
      sha256 "df7396019416ac622fde913ec6456f2b4b4a6ea940a6471c3f93e486c542aa9a"
      binary "gitlab-backup_1.16.0_darwin_arm64", target: "gitlab-backup"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/sgaunet/gitlab-backup/releases/download/v#{version}/gitlab-backup_#{version}_linux_amd64"
      sha256 "37ae16fe601abe367f5d7dfbe9cf92312a09233dcb14d0fe04dedeec9fb4c9ed"
      binary "gitlab-backup_1.16.0_linux_amd64", target: "gitlab-backup"
    end
    on_arm do
      url "https://github.com/sgaunet/gitlab-backup/releases/download/v#{version}/gitlab-backup_#{version}_linux_arm64"
      sha256 "81dd96d5cbb126029bb2807960fd7267b73118be543bf9e20389fedfd87c2c46"
      binary "gitlab-backup_1.16.0_linux_arm64", target: "gitlab-backup"
    end
  end

  # No zap stanza required
end
