# This file was generated by GoReleaser. DO NOT EDIT.
cask "gocrypt" do
  version "2.0.3"

  on_macos do
    on_intel do
      sha256 "1a431bfe99e934a0d17a29297250bfc8b6248e561f6e9c63c703412130bf2bdc"
      url "https://github.com/sgaunet/gocrypt/releases/download/v#{version}/gocrypt_#{version}_darwin_amd64"
      binary "gocrypt_2.0.3_darwin_amd64", target: "gocrypt"
    end
    on_arm do
      sha256 "afd9eada377f046fb6174070b52478e6d41701318a8369b41c9eb7d5099c4267"
      url "https://github.com/sgaunet/gocrypt/releases/download/v#{version}/gocrypt_#{version}_darwin_arm64"
      binary "gocrypt_2.0.3_darwin_arm64", target: "gocrypt"
    end
  end

  on_linux do
    on_intel do
      sha256 "e2d4f2ebd9d62a5e053152f13c40b90c43be555d2f57266905c334f83a34f6f6"
      url "https://github.com/sgaunet/gocrypt/releases/download/v#{version}/gocrypt_#{version}_linux_amd64"
      binary "gocrypt_2.0.3_linux_amd64", target: "gocrypt"
    end
    on_arm do
      sha256 "5c6c4893af8256dd2129f63fc68bf09b0a756dbfabd7d2975a19ef2be44a9823"
      url "https://github.com/sgaunet/gocrypt/releases/download/v#{version}/gocrypt_#{version}_linux_arm64"
      binary "gocrypt_2.0.3_linux_arm64", target: "gocrypt"
    end
  end

  name "gocrypt"
  desc "Encrypt and decrypt files using AES-128 or AES-256 in GCM mode"
  homepage "https://github.com/sgaunet/gocrypt"

  livecheck do
    skip "Auto-generated on release."
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}"]
    end
  end

  # No zap stanza required

end
