# This file was generated by GoReleaser. DO NOT EDIT.
cask "helmchart-helper" do
  version "0.3.1"

  on_macos do
    on_intel do
      sha256 "a2f7af780f01c688d9e86f56e98b9521ff41a1d9e9ecaab4915c6dd0c627d2b3"
      url "https://github.com/sgaunet/helmchart-helper/releases/download/v#{version}/helmchart-helper_#{version}_darwin_amd64"
      binary "helmchart-helper_0.3.1_darwin_amd64", target: "helmchart-helper"
    end
    on_arm do
      sha256 "3fd298c949b21c23a6cfa11a4bc893760f9a7f15fb55c2eede6fd1a9cc554e78"
      url "https://github.com/sgaunet/helmchart-helper/releases/download/v#{version}/helmchart-helper_#{version}_darwin_arm64"
      binary "helmchart-helper_0.3.1_darwin_arm64", target: "helmchart-helper"
    end
  end

  on_linux do
    on_intel do
      sha256 "06ec3d3e5df88963f18a44e5bb6c460c873098ad4cee7098f8d56ad2ea419748"
      url "https://github.com/sgaunet/helmchart-helper/releases/download/v#{version}/helmchart-helper_#{version}_linux_amd64"
      binary "helmchart-helper_0.3.1_linux_amd64", target: "helmchart-helper"
    end
    on_arm do
      sha256 "45852791178f23f01a08186644a7c13293239025979287686d88f5137fdc138f"
      url "https://github.com/sgaunet/helmchart-helper/releases/download/v#{version}/helmchart-helper_#{version}_linux_arm64"
      binary "helmchart-helper_0.3.1_linux_arm64", target: "helmchart-helper"
    end
  end

  name "helmchart-helper"
  desc "Generate basic Helm charts for Kubernetes applications"
  homepage "https://github.com/sgaunet/helmchart-helper"

  livecheck do
    skip "Auto-generated on release."
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}"]
    end
  end

  # No zap stanza required

end
