# This file was generated by GoReleaser. DO NOT EDIT.
cask "jwt-cli" do
  name "jwt-cli"
  desc "CLI tool for encoding and decoding JWT tokens"
  homepage "https://github.com/sgaunet/jwt-cli"
  version "1.5.1"

  livecheck do
    skip "Auto-generated on release."
  end

  on_macos do
    on_intel do
      url "https://github.com/sgaunet/jwt-cli/releases/download/v#{version}/jwt-cli_#{version}_darwin_amd64"
      sha256 "1e8e06369f10a3941860d6c5d3ea74e7f7fad046b943c2bc07c6a640cc135b6c"
      binary "jwt-cli_1.5.1_darwin_amd64", target: "jwt-cli"
    end
    on_arm do
      url "https://github.com/sgaunet/jwt-cli/releases/download/v#{version}/jwt-cli_#{version}_darwin_arm64"
      sha256 "07600e77287c82d76df18d468b1605437d91704f79bb5c22b6d7144b87aa2306"
      binary "jwt-cli_1.5.1_darwin_arm64", target: "jwt-cli"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/sgaunet/jwt-cli/releases/download/v#{version}/jwt-cli_#{version}_linux_amd64"
      sha256 "de271b12227701aebc7ba19c7634c7239756fd3e9137fb4bf600a210a2276208"
      binary "jwt-cli_1.5.1_linux_amd64", target: "jwt-cli"
    end
    on_arm do
      url "https://github.com/sgaunet/jwt-cli/releases/download/v#{version}/jwt-cli_#{version}_linux_arm64"
      sha256 "e1631cc4a7bbd21fccf8122cea014f929197b7c1a22793f26c73650693dac02c"
      binary "jwt-cli_1.5.1_linux_arm64", target: "jwt-cli"
    end
  end

  # No zap stanza required
end
