# This file was generated by GoReleaser. DO NOT EDIT.
cask "jwt-cli" do
  version "1.5.2"

  on_macos do
    on_intel do
      sha256 "879db07221d448526ed8eced849e13a745f72a33471242aafc6ffab4ef276cae"
      url "https://github.com/sgaunet/jwt-cli/releases/download/v#{version}/jwt-cli_#{version}_darwin_amd64"
      binary "jwt-cli_1.5.2_darwin_amd64", target: "jwt-cli"
    end
    on_arm do
      sha256 "1e67aaa206eba486c015706b451e81bc2bec6bcfef02d52047e1eddaae212f55"
      url "https://github.com/sgaunet/jwt-cli/releases/download/v#{version}/jwt-cli_#{version}_darwin_arm64"
      binary "jwt-cli_1.5.2_darwin_arm64", target: "jwt-cli"
    end
  end

  on_linux do
    on_intel do
      sha256 "a0d8d04e722364c5666a84e30a7b1c5d6dc71086e62fcb814de18082e48d57c6"
      url "https://github.com/sgaunet/jwt-cli/releases/download/v#{version}/jwt-cli_#{version}_linux_amd64"
      binary "jwt-cli_1.5.2_linux_amd64", target: "jwt-cli"
    end
    on_arm do
      sha256 "08d48ea62e5b2183994bd0da3696366a12147217cabe786b1a604dcca05f29a4"
      url "https://github.com/sgaunet/jwt-cli/releases/download/v#{version}/jwt-cli_#{version}_linux_arm64"
      binary "jwt-cli_1.5.2_linux_arm64", target: "jwt-cli"
    end
  end

  name "jwt-cli"
  desc "CLI tool for encoding and decoding JWT tokens"
  homepage "https://github.com/sgaunet/jwt-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  # No zap stanza required

end
