# This file was generated by GoReleaser. DO NOT EDIT.
cask "jwt-cli" do
  version "1.6.0"

  on_macos do
    on_intel do
      sha256 "326ec6661fa58fc006cf5854449340e1b8a8773ef943932e54b6cc8fdc051d23"
      url "https://github.com/sgaunet/jwt-cli/releases/download/v#{version}/jwt-cli_#{version}_darwin_amd64"
      binary "jwt-cli_1.6.0_darwin_amd64", target: "jwt-cli"
    end
    on_arm do
      sha256 "29c6fe3ab92bc631431a61a376acbab6b3df16ab177e64e6e4aefc0d4fa5aee2"
      url "https://github.com/sgaunet/jwt-cli/releases/download/v#{version}/jwt-cli_#{version}_darwin_arm64"
      binary "jwt-cli_1.6.0_darwin_arm64", target: "jwt-cli"
    end
  end

  on_linux do
    on_intel do
      sha256 "94c07276559067e8b1d5b2578efb7caaa107fee75ba4a98987172f9c65b47a20"
      url "https://github.com/sgaunet/jwt-cli/releases/download/v#{version}/jwt-cli_#{version}_linux_amd64"
      binary "jwt-cli_1.6.0_linux_amd64", target: "jwt-cli"
    end
    on_arm do
      sha256 "b19b632aa4b5ac1195ed2973c696742fb60950819d697b0534f9a12af24e256b"
      url "https://github.com/sgaunet/jwt-cli/releases/download/v#{version}/jwt-cli_#{version}_linux_arm64"
      binary "jwt-cli_1.6.0_linux_arm64", target: "jwt-cli"
    end
  end

  name "jwt-cli"
  desc "CLI tool for encoding and decoding JWT tokens"
  homepage "https://github.com/sgaunet/jwt-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  # No zap stanza required

end
