# This file was generated by GoReleaser. DO NOT EDIT.
cask "logwrap" do
  version "0.4.0"

  on_macos do
    on_intel do
      sha256 "441e909ab7bde4953f840ebd5a2275815ff79dcec1e140c1b2c045c2932fcbc0"
      url "https://github.com/sgaunet/logwrap/releases/download/v#{version}/logwrap_#{version}_darwin_amd64"
      binary "logwrap_0.4.0_darwin_amd64", target: "logwrap"
    end
    on_arm do
      sha256 "3c47a96ba44e0ad359f5a3ba698e9a3aaec933285f7480a747dba0c6df11d705"
      url "https://github.com/sgaunet/logwrap/releases/download/v#{version}/logwrap_#{version}_darwin_arm64"
      binary "logwrap_0.4.0_darwin_arm64", target: "logwrap"
    end
  end

  on_linux do
    on_intel do
      sha256 "b8008bdf1d47f09d5a5566cf97c37c321d655efacaa9fc1517782be1a1ba6208"
      url "https://github.com/sgaunet/logwrap/releases/download/v#{version}/logwrap_#{version}_linux_amd64"
      binary "logwrap_0.4.0_linux_amd64", target: "logwrap"
    end
    on_arm do
      sha256 "346e68dace108556ee636a98fcd71dd8624f3fc92c1c196082c06b73d7ed012b"
      url "https://github.com/sgaunet/logwrap/releases/download/v#{version}/logwrap_#{version}_linux_arm64"
      binary "logwrap_0.4.0_linux_arm64", target: "logwrap"
    end
  end

  name "logwrap"
  desc "Command wrapper that adds configurable prefixes to stdout and stderr"
  homepage "https://github.com/sgaunet/logwrap"

  livecheck do
    skip "Auto-generated on release."
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}"]
    end
  end

  # No zap stanza required

end
