# This file was generated by GoReleaser. DO NOT EDIT.
cask "mdtohtml" do
  version "1.2.1"

  on_macos do
    on_intel do
      sha256 "51fa6a43dca9175f866074be7f5f14b85d21676d77aa531f4269e5c36a230efa"
      url "https://github.com/sgaunet/mdtohtml/releases/download/v#{version}/mdtohtml_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "fa6f5d0fd6678c854f3f91afbb7035c95d5718d7cd515a0c4d57fac4b2a953f5"
      url "https://github.com/sgaunet/mdtohtml/releases/download/v#{version}/mdtohtml_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d206b9d88dccf3668158714ab0dba2017a8a2702bfed92409d13a25fff1c703c"
      url "https://github.com/sgaunet/mdtohtml/releases/download/v#{version}/mdtohtml_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "875db9ea9d6bd10276ac79977ba50bbf41c5adfff649e199d4b30724adbcf274"
      url "https://github.com/sgaunet/mdtohtml/releases/download/v#{version}/mdtohtml_#{version}_linux_arm64.tar.gz"
    end
  end

  name "mdtohtml"
  desc "Simple and efficient Markdown to HTML converter"
  homepage "https://github.com/sgaunet/mdtohtml"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mdtohtml"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}"]
    end
  end

  # No zap stanza required

end
