# This file was generated by GoReleaser. DO NOT EDIT.
cask "moraine" do
  version "0.4.0"

  on_macos do
    on_intel do
      sha256 "6434a54eef90a79f11af37d1f418ccc77a0499d312b9706609a42a5dc1e8e2a2"
      url "https://github.com/sgaunet/moraine/releases/download/v#{version}/moraine_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "4b8915e2078b18dca517a3f88ab5f3fce8734dcda485c868b3783c639b97e133"
      url "https://github.com/sgaunet/moraine/releases/download/v#{version}/moraine_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "bfab85cff78244410719a4956517a38c487fd14ba456af5367bd6cb7d0fde513"
      url "https://github.com/sgaunet/moraine/releases/download/v#{version}/moraine_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "dcdd30f0c42a29f34f1023713f681813b2a9d314f5a7f89bfcfa99c238f31900"
      url "https://github.com/sgaunet/moraine/releases/download/v#{version}/moraine_#{version}_linux_arm64.tar.gz"
    end
  end

  name "moraine"
  desc "Organize photos into event folders by capture time and theme"
  homepage "https://github.com/sgaunet/moraine"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "exiftool",
    ]

  binary "moraine"

  preflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", staged_path]
    end
  end

  generate_completions_from_executable "moraine",
    shell_parameter_format: :cobra

  # No zap stanza required

end
