# This file was generated by GoReleaser. DO NOT EDIT.
cask "moraine" do
  version "0.6.0"

  on_macos do
    on_intel do
      sha256 "0da42e7c48544fea5af9c10984926bff7e8822ca734ff6345c92a184a597a494"
      url "https://github.com/sgaunet/moraine/releases/download/v#{version}/moraine_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "9288a1b7416c82aa08c6ac2bba16f827cb56c3c31d6f52eef8901ca408f1fa64"
      url "https://github.com/sgaunet/moraine/releases/download/v#{version}/moraine_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "8fb748843b312d60b642236d1734588a7bf6993e61fd7562e2fc60a323505228"
      url "https://github.com/sgaunet/moraine/releases/download/v#{version}/moraine_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "cecf12f64e9316b8ba170736dada894efec884e555b64b1abe95afb0be5dabd7"
      url "https://github.com/sgaunet/moraine/releases/download/v#{version}/moraine_#{version}_linux_arm64.tar.gz"
    end
  end

  name "moraine"
  desc "Organize photos into event folders by capture time and theme"
  homepage "https://github.com/sgaunet/moraine"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "exiftool",
    ]

  binary "moraine"

  preflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", staged_path]
    end
  end

  generate_completions_from_executable "moraine",
    shell_parameter_format: :cobra

  # No zap stanza required

end
