# This file was generated by GoReleaser. DO NOT EDIT.
cask "moraine" do
  version "0.5.0"

  on_macos do
    on_intel do
      sha256 "27c41d3997c7ca47f9d829c250c7505e53154661653503c059d0c53113f4c6a5"
      url "https://github.com/sgaunet/moraine/releases/download/v#{version}/moraine_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "1e8363571fff30b18bb03e86dbf3d542336d46b9f8f17dd49c27ee7f9f9f0562"
      url "https://github.com/sgaunet/moraine/releases/download/v#{version}/moraine_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "fbcaf331a5073ed887eea8c17cb9bcfdbba994354cdecbf06e610917a62faf7f"
      url "https://github.com/sgaunet/moraine/releases/download/v#{version}/moraine_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "22d73b42125ebd3ed507497550666e56870699eb439e04cda3e43f524589031c"
      url "https://github.com/sgaunet/moraine/releases/download/v#{version}/moraine_#{version}_linux_arm64.tar.gz"
    end
  end

  name "moraine"
  desc "Organize photos into event folders by capture time and theme"
  homepage "https://github.com/sgaunet/moraine"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "exiftool",
    ]

  binary "moraine"

  preflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", staged_path]
    end
  end

  generate_completions_from_executable "moraine",
    shell_parameter_format: :cobra

  # No zap stanza required

end
