# This file was generated by GoReleaser. DO NOT EDIT.
cask "postgresql-mcp" do
  version "0.5.3"

  on_macos do
    on_intel do
      sha256 "471ad96b2dc6562d5e5899bb7379b0f39835361aaed31e281e1b737314826270"
      url "https://github.com/sgaunet/postgresql-mcp/releases/download/v#{version}/postgresql-mcp_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "7b3462fba7aa2312c24d850b3d8843e39674f4773e7893c2871a9475f12a8361"
      url "https://github.com/sgaunet/postgresql-mcp/releases/download/v#{version}/postgresql-mcp_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "5afa849057491bdf7561e2fda3fc41a1bf6e83daca0361b79993111747962f67"
      url "https://github.com/sgaunet/postgresql-mcp/releases/download/v#{version}/postgresql-mcp_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "2f4df9e5d892a4a110139f5d1f6a5729ef2ca9a7d5796adc841b124068b7327a"
      url "https://github.com/sgaunet/postgresql-mcp/releases/download/v#{version}/postgresql-mcp_#{version}_linux_arm64.tar.gz"
    end
  end

  name "postgresql-mcp"
  desc "Model Context Protocol server with PostgreSQL integration tools for MCP clients"
  homepage "https://github.com/sgaunet/postgresql-mcp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "postgresql-mcp"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}"]
    end
  end

  # No zap stanza required

end
