# This file was generated by GoReleaser. DO NOT EDIT.
cask "pplx" do
  version "0.11.1"

  on_macos do
    on_intel do
      sha256 "cc8695ca0e52142c8f9bce6648f0e868f4ca3ccbfe454c77431bb9ae6a8468a1"
      url "https://github.com/sgaunet/pplx/releases/download/v#{version}/pplx_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b6ada95ef2b7dc0c86f2eb2ae71cbc1af964283a572df3ab7542bdc276104899"
      url "https://github.com/sgaunet/pplx/releases/download/v#{version}/pplx_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "aa71ed10c097044e262c7acbd0620fefff4a3fad973acdb4685f47db0df06242"
      url "https://github.com/sgaunet/pplx/releases/download/v#{version}/pplx_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "031948ffd770d53a086374e9204cc06ab1e30c372ed7d947d3530ce74fd9f181"
      url "https://github.com/sgaunet/pplx/releases/download/v#{version}/pplx_#{version}_linux_arm64.tar.gz"
    end
  end

  name "pplx"
  desc "Unofficial CLI to query and chat with the Perplexity API"
  homepage "https://github.com/sgaunet/pplx"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pplx"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pplx"]
    end
  end
  generate_completions_from_executable "pplx", "completion",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required

end
