# This file was generated by GoReleaser. DO NOT EDIT.
cask "pplx" do
  version "0.11.4"

  on_macos do
    on_intel do
      sha256 "bc80538e1131a15140ab8c0191c9cd4025c0ae311a761eb15df8f317091dda4d"
      url "https://github.com/sgaunet/pplx/releases/download/v#{version}/pplx_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "ea5865132688aa1a7ee6695e80fc38128818ad4e3878378ecc8a6d13f431efc4"
      url "https://github.com/sgaunet/pplx/releases/download/v#{version}/pplx_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "025be7b44427a83a9cc3ba5266f856629941c8cb3c9490ca2a9578793bcf045e"
      url "https://github.com/sgaunet/pplx/releases/download/v#{version}/pplx_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "0f103543edfb85362c86854aec2e01c6e370b2da3c1acf5c8152d0fc84e5ef1b"
      url "https://github.com/sgaunet/pplx/releases/download/v#{version}/pplx_#{version}_linux_arm64.tar.gz"
    end
  end

  name "pplx"
  desc "Unofficial CLI to query and chat with the Perplexity API"
  homepage "https://github.com/sgaunet/pplx"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pplx"

  preflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pplx"]
    end
  end

  generate_completions_from_executable "pplx", "completion",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required

end
