# This file was generated by GoReleaser. DO NOT EDIT.
cask "pplx" do
  version "0.11.5"

  on_macos do
    on_intel do
      sha256 "6d6b4b3c7c94ebfe52703db79e8d1eee8a8192b20f99bceb19b195a2d803ed3d"
      url "https://github.com/sgaunet/pplx/releases/download/v#{version}/pplx_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "4643f12c1ee389b92e62e695e519cd0596bce4a6c59e337af9bb7252391eb10c"
      url "https://github.com/sgaunet/pplx/releases/download/v#{version}/pplx_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "59d00fc7cd49b9c0af9283e406de0ec565db69b0bb6e1b7a83c9e79ec6981691"
      url "https://github.com/sgaunet/pplx/releases/download/v#{version}/pplx_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "56773264c7f3d2003210689ea134b64da4db5feebc3cf858fe9e6cbe284c2aef"
      url "https://github.com/sgaunet/pplx/releases/download/v#{version}/pplx_#{version}_linux_arm64.tar.gz"
    end
  end

  name "pplx"
  desc "Unofficial CLI to query and chat with the Perplexity API"
  homepage "https://github.com/sgaunet/pplx"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pplx"

  preflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pplx"]
    end
  end

  generate_completions_from_executable "pplx", "completion",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required

end
