# This file was generated by GoReleaser. DO NOT EDIT.
cask "restic-age-key" do
  version "0.1.3"

  on_macos do
    on_intel do
      sha256 "02ff0d9fc74b17e54547e51ab88c243ada055ce6dcb5e37c59b0b7aa4a927144"
      url "https://github.com/sgaunet/restic-age-key/releases/download/v#{version}/restic-age-key_#{version}_darwin_amd64"
      binary "restic-age-key_0.1.3_darwin_amd64", target: "restic-age-key"
    end
    on_arm do
      sha256 "a4c4072a6780b4c9c9b95d8a8085fc3dab575212850ea55b03828c0bd62973fe"
      url "https://github.com/sgaunet/restic-age-key/releases/download/v#{version}/restic-age-key_#{version}_darwin_arm64"
      binary "restic-age-key_0.1.3_darwin_arm64", target: "restic-age-key"
    end
  end

  on_linux do
    on_intel do
      sha256 "d84c0419fed6897f655b10741dcf4401806a300864329731e08ebfbbf183ba7f"
      url "https://github.com/sgaunet/restic-age-key/releases/download/v#{version}/restic-age-key_#{version}_linux_amd64"
      binary "restic-age-key_0.1.3_linux_amd64", target: "restic-age-key"
    end
    on_arm do
      sha256 "9a7b18a3685a19b18ad6572d78d7cd69a8b0342a4483f645351000402d7e020e"
      url "https://github.com/sgaunet/restic-age-key/releases/download/v#{version}/restic-age-key_#{version}_linux_arm64"
      binary "restic-age-key_0.1.3_linux_arm64", target: "restic-age-key"
    end
  end

  name "restic-age-key"
  desc "Unlock restic repositories with asymmetric age keys instead of a password"
  homepage "https://github.com/sgaunet/restic-age-key"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "age",
    ]

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}"]
    end
  end

  # No zap stanza required

end
