# This file was generated by GoReleaser. DO NOT EDIT.
cask "scaffold" do
  version "0.5.0"

  on_macos do
    on_intel do
      sha256 "5857e08d11aa9d7db1bb4b0809d92118b127755b75e8c3737c6736ab91365014"
      url "https://github.com/sgaunet/scaffold/releases/download/v#{version}/scaffold_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "a63180a2f8add6ac11558258725df2d5a3b49379c77e9a2437f02add98fd1cc1"
      url "https://github.com/sgaunet/scaffold/releases/download/v#{version}/scaffold_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ae50c1f4461265adbb1c559efe5d69ffe5c6feb2827ea40b5489df515376379f"
      url "https://github.com/sgaunet/scaffold/releases/download/v#{version}/scaffold_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "373b871debde399b646c528c754064704ee49a095e7707a672d1010cc4661af8"
      url "https://github.com/sgaunet/scaffold/releases/download/v#{version}/scaffold_#{version}_linux_arm64.tar.gz"
    end
  end

  name "scaffold"
  desc "scaffold"
  homepage "https://github.com/sgaunet/scaffold"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "scaffold"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}"]
    end
  end
  generate_completions_from_executable "scaffold", "completion",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required

end
