# This file was generated by GoReleaser. DO NOT EDIT.
cask "scaffold" do
  version "0.4.1"

  on_macos do
    on_intel do
      sha256 "c4622d861ca8e235c2c68f82a7d5384cbc1ff91f9f50d9f5e3cd4278744cf47a"
      url "https://github.com/sgaunet/scaffold/releases/download/v#{version}/scaffold_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "dbe8dd77e2d44a261a40a95f25a47eb3b24b4a4decf863d043e5f580f0542e68"
      url "https://github.com/sgaunet/scaffold/releases/download/v#{version}/scaffold_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b2d2f3a02761d8317504cf442a119914a8188806eb030daf8b6af36996c7595f"
      url "https://github.com/sgaunet/scaffold/releases/download/v#{version}/scaffold_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "333487e267ce1f5f238cfe4bdd1c7833849c7660631ebb34628f2dd7e62f6e41"
      url "https://github.com/sgaunet/scaffold/releases/download/v#{version}/scaffold_#{version}_linux_arm64.tar.gz"
    end
  end

  name "scaffold"
  desc "scaffold"
  homepage "https://github.com/sgaunet/scaffold"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "scaffold"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}"]
    end
  end
  generate_completions_from_executable "scaffold", "completion",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required

end
