# This file was generated by GoReleaser. DO NOT EDIT.
cask "scaffold" do
  version "0.4.4"

  on_macos do
    on_intel do
      sha256 "a1cdb03fabe87c535dc78b5cb0516465f6e87f1f82a38c25e651fcb3a406517b"
      url "https://github.com/sgaunet/scaffold/releases/download/v#{version}/scaffold_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "087f2ce56bbbcb85d7183496b53c6a7e5429f82bcedd2381056304d07c77cbf3"
      url "https://github.com/sgaunet/scaffold/releases/download/v#{version}/scaffold_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "135b8cbfd560f7924c0dfa87f78dbb2ee04f7dab6180f3a9a658f147df947af5"
      url "https://github.com/sgaunet/scaffold/releases/download/v#{version}/scaffold_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "bbf23a97764e2081870f43a25b522fc788a70fe0501fe6d0aa26f7e06494469b"
      url "https://github.com/sgaunet/scaffold/releases/download/v#{version}/scaffold_#{version}_linux_arm64.tar.gz"
    end
  end

  name "scaffold"
  desc "scaffold"
  homepage "https://github.com/sgaunet/scaffold"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "scaffold"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}"]
    end
  end
  generate_completions_from_executable "scaffold", "completion",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required

end
