# This file was generated by GoReleaser. DO NOT EDIT.
cask "semver" do
  version "0.1.4"

  on_macos do
    on_intel do
      sha256 "df502e37875a2415f0b2fd631258e2aac93461e03c3861b75c366d54b281411d"
      url "https://github.com/sgaunet/semver/releases/download/v#{version}/semver_#{version}_darwin_x86_64"
      binary "semver_0.1.4_darwin_x86_64", target: "semver"
    end
    on_arm do
      sha256 "03a977b21851a2658aa5b79e73e35591bcf1eeebc91f83a5045fe4b9306d3496"
      url "https://github.com/sgaunet/semver/releases/download/v#{version}/semver_#{version}_darwin_arm64"
      binary "semver_0.1.4_darwin_arm64", target: "semver"
    end
  end

  on_linux do
    on_intel do
      sha256 "3e67b561e41b45d482f1121fa61d8a9d56c2a8b0d622e01c52198cb0569dc37d"
      url "https://github.com/sgaunet/semver/releases/download/v#{version}/semver_#{version}_linux_x86_64"
      binary "semver_0.1.4_linux_x86_64", target: "semver"
    end
    on_arm do
      sha256 "b37c281178ebb7b20f109fe4419ae89a468dc44239724f779d153c108f0aff72"
      url "https://github.com/sgaunet/semver/releases/download/v#{version}/semver_#{version}_linux_arm64"
      binary "semver_0.1.4_linux_arm64", target: "semver"
    end
  end

  name "semver"
  desc "Semantic version CLI to bump, compare, sort, validate, and check version constraints"
  homepage "https://github.com/sgaunet/semver"

  livecheck do
    skip "Auto-generated on release."
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}"]
    end
  end

  # No zap stanza required

end
