# This file was generated by GoReleaser. DO NOT EDIT.
cask "semver" do
  version "0.1.2"

  on_macos do
    on_intel do
      sha256 "613e9ee414ef5c7d876f546a1493ed602c46dd809cfc242ed395352a6f0dd307"
      url "https://github.com/sgaunet/semver/releases/download/v#{version}/semver_#{version}_darwin_x86_64"
      binary "semver_0.1.2_darwin_x86_64", target: "semver"
    end
    on_arm do
      sha256 "e30745ce5e3e77762f8d7aca2354b1a0228fbb63bfadeda3afa4e48fb6bd9bba"
      url "https://github.com/sgaunet/semver/releases/download/v#{version}/semver_#{version}_darwin_arm64"
      binary "semver_0.1.2_darwin_arm64", target: "semver"
    end
  end

  on_linux do
    on_intel do
      sha256 "7e0b90e240a67a958d57b5ede1bde5f2d75769a8f5cfbc0d8b8c2453f9c4020d"
      url "https://github.com/sgaunet/semver/releases/download/v#{version}/semver_#{version}_linux_x86_64"
      binary "semver_0.1.2_linux_x86_64", target: "semver"
    end
    on_arm do
      sha256 "6c46404126cbb0c88f7455bfa3789056004b8e20b73cd75bdb5b8fcd30a5bc65"
      url "https://github.com/sgaunet/semver/releases/download/v#{version}/semver_#{version}_linux_arm64"
      binary "semver_0.1.2_linux_arm64", target: "semver"
    end
  end

  name "semver"
  desc "Semantic version CLI to bump, compare, sort, validate, and check version constraints"
  homepage "https://github.com/sgaunet/semver"

  livecheck do
    skip "Auto-generated on release."
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/semver"]
    end
  end

  # No zap stanza required

end
