# This file was generated by GoReleaser. DO NOT EDIT.
cask "semver" do
  version "0.1.3"

  on_macos do
    on_intel do
      sha256 "7c0f291fddd36a47247ede40d40f7faea97bf55b9a69c2be0e3188ef539409c2"
      url "https://github.com/sgaunet/semver/releases/download/v#{version}/semver_#{version}_darwin_x86_64"
      binary "semver_0.1.3_darwin_x86_64", target: "semver"
    end
    on_arm do
      sha256 "ed9b6e0aa4a8ab78e78f30d69daa35e4e257013c09ef6752e1e33b90ec43fda9"
      url "https://github.com/sgaunet/semver/releases/download/v#{version}/semver_#{version}_darwin_arm64"
      binary "semver_0.1.3_darwin_arm64", target: "semver"
    end
  end

  on_linux do
    on_intel do
      sha256 "8186ebdb22f6098f9d92c806aa944ee8900f1a639eb4c9a6e8bc068e1863b27d"
      url "https://github.com/sgaunet/semver/releases/download/v#{version}/semver_#{version}_linux_x86_64"
      binary "semver_0.1.3_linux_x86_64", target: "semver"
    end
    on_arm do
      sha256 "fbf41a039b0e7c2db1f9fed57730daf44e8a81d5626f10c9648159803d91f6e8"
      url "https://github.com/sgaunet/semver/releases/download/v#{version}/semver_#{version}_linux_arm64"
      binary "semver_0.1.3_linux_arm64", target: "semver"
    end
  end

  name "semver"
  desc "Semantic version CLI to bump, compare, sort, validate, and check version constraints"
  homepage "https://github.com/sgaunet/semver"

  livecheck do
    skip "Auto-generated on release."
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/semver"]
    end
  end

  # No zap stanza required

end
