# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AutoMr < Formula
  desc ""
  homepage "https://github.com/sgaunet/auto-mr"
  version "0.13.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sgaunet/auto-mr/releases/download/v0.13.1/auto-mr_0.13.1_darwin_amd64"
      sha256 "d254bd936d2c1af662297c4b9a1f61388f973161491001341f3de96c1ed8e600"

      define_method(:install) do
        bin.install "auto-mr_0.13.1_darwin_amd64" => "auto-mr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sgaunet/auto-mr/releases/download/v0.13.1/auto-mr_0.13.1_darwin_arm64"
      sha256 "e49b87826638b590364b4db85b0eb23fb6c9cb972edfa358c04565c0d1cff953"

      define_method(:install) do
        bin.install "auto-mr_0.13.1_darwin_arm64" => "auto-mr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sgaunet/auto-mr/releases/download/v0.13.1/auto-mr_0.13.1_linux_amd64"
      sha256 "45f4dabd896ea6384d8571c4a1352b5f09489cf849526e494dde5dd7e1447f2c"
      define_method(:install) do
        bin.install "auto-mr_0.13.1_linux_amd64" => "auto-mr"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/sgaunet/auto-mr/releases/download/v0.13.1/auto-mr_0.13.1_linux_armv6"
      sha256 "ca3238e189495f75ccb4b0758b5211c54f14568fea52d6a3b4de36630d1563e2"
      define_method(:install) do
        bin.install "auto-mr_0.13.1_linux_armv6" => "auto-mr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sgaunet/auto-mr/releases/download/v0.13.1/auto-mr_0.13.1_linux_arm64"
      sha256 "a356de7a964a08536c7c20e83d9613c4793594de635e423a96fb35feaee17ca4"
      define_method(:install) do
        bin.install "auto-mr_0.13.1_linux_arm64" => "auto-mr"
      end
    end
  end

  test do
    system "#{bin}/auto-mr", "--help"
  end
end
