# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AutoMr < Formula
  desc ""
  homepage "https://github.com/sgaunet/auto-mr"
  version "0.6.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sgaunet/auto-mr/releases/download/v0.6.1/auto-mr_0.6.1_darwin_amd64"
      sha256 "93fdba24f70fcec08c17d78446228b92440c5c1adf6d47572ad29c3b5ec050f8"

      def install
        bin.install "auto-mr_0.6.1_darwin_amd64" => "auto-mr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sgaunet/auto-mr/releases/download/v0.6.1/auto-mr_0.6.1_darwin_arm64"
      sha256 "56a45c651969b8cebc0324fec04cebe1a96fc04fbf2022daaaa9c054629754f7"

      def install
        bin.install "auto-mr_0.6.1_darwin_arm64" => "auto-mr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sgaunet/auto-mr/releases/download/v0.6.1/auto-mr_0.6.1_linux_amd64"
      sha256 "2ae8d3174518dffbf332f13deaea61c4f07395b23e0aac4d5b5b382496d5dae6"
      def install
        bin.install "auto-mr_0.6.1_linux_amd64" => "auto-mr"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/sgaunet/auto-mr/releases/download/v0.6.1/auto-mr_0.6.1_linux_armv6"
      sha256 "c2ddaf387952d9331ad4d5b6bb15f0bb96307170dd454841f1c89f20d1993104"
      def install
        bin.install "auto-mr_0.6.1_linux_armv6" => "auto-mr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sgaunet/auto-mr/releases/download/v0.6.1/auto-mr_0.6.1_linux_arm64"
      sha256 "8a48e0bf580f9d8596c3830a5a08356a69a597cb71ce68891661d65a5e74543f"
      def install
        bin.install "auto-mr_0.6.1_linux_arm64" => "auto-mr"
      end
    end
  end

  test do
    system "#{bin}/auto-mr", "--help"
  end
end
