# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AutoMr < Formula
  desc ""
  homepage "https://github.com/sgaunet/auto-mr"
  version "0.9.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sgaunet/auto-mr/releases/download/v0.9.1/auto-mr_0.9.1_darwin_amd64"
      sha256 "45012ed92f6d823eedcc6e28a37d79f13feff8b5fa1d34c497b2fe8e3e06306f"

      def install
        bin.install "auto-mr_0.9.1_darwin_amd64" => "auto-mr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sgaunet/auto-mr/releases/download/v0.9.1/auto-mr_0.9.1_darwin_arm64"
      sha256 "02a4787b08ed1960015a16e2813100e5631d60647eef377c1e1f474ad0bebe2a"

      def install
        bin.install "auto-mr_0.9.1_darwin_arm64" => "auto-mr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sgaunet/auto-mr/releases/download/v0.9.1/auto-mr_0.9.1_linux_amd64"
      sha256 "b14f622a6293b8634984fa28148f030438853cf705116594612ba5e114787282"
      def install
        bin.install "auto-mr_0.9.1_linux_amd64" => "auto-mr"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/sgaunet/auto-mr/releases/download/v0.9.1/auto-mr_0.9.1_linux_armv6"
      sha256 "6072a22c1e1efbefe61594e4730cdc9fdbd072a5868edd5f1ac9cffa6ac8ca32"
      def install
        bin.install "auto-mr_0.9.1_linux_armv6" => "auto-mr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sgaunet/auto-mr/releases/download/v0.9.1/auto-mr_0.9.1_linux_arm64"
      sha256 "c575ec01730fe2c7fbdb46957c2b97fdabe3737a7f1c6fbe586a2da7f49dc543"
      def install
        bin.install "auto-mr_0.9.1_linux_arm64" => "auto-mr"
      end
    end
  end

  test do
    system "#{bin}/auto-mr", "--help"
  end
end
