# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Calcdate < Formula
  desc ""
  homepage "https://github.com/sgaunet/homebrew-tools"
  version "1.4.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/sgaunet/calcdate/releases/download/v1.4.2/calcdate_1.4.2_Darwin_arm64"
      sha256 "0f626e55510346a3f07d49693cc622343fe343de2a725dd79a8d1c5a89eb0c96"

      def install
        bin.install "calcdate_1.4.2_Darwin_arm64" => "calcdate"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sgaunet/calcdate/releases/download/v1.4.2/calcdate_1.4.2_Darwin_x86_64"
      sha256 "abd6bc57a28aa859bc40091d2cac03aef820563b42e67bbc04f4468a871c645c"

      def install
        bin.install "calcdate_1.4.2_Darwin_x86_64" => "calcdate"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/sgaunet/calcdate/releases/download/v1.4.2/calcdate_1.4.2_Linux_armv6"
      sha256 "3f6a909cac8a8c74dbd530fe75f8b308b2f76f00121905c9e29bbe51709f21f5"

      def install
        bin.install "calcdate_1.4.2_Linux_armv6" => "calcdate"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sgaunet/calcdate/releases/download/v1.4.2/calcdate_1.4.2_Linux_arm64"
      sha256 "324980c2595f1a87579b2c931dacddcb778d330d41a8baf88bc660b76cd7c210"

      def install
        bin.install "calcdate_1.4.2_Linux_arm64" => "calcdate"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sgaunet/calcdate/releases/download/v1.4.2/calcdate_1.4.2_Linux_x86_64"
      sha256 "7dcef41a7f665151407d01e926ba76377f56f46caf2d0aabb518defa5805ea5d"

      def install
        bin.install "calcdate_1.4.2_Linux_x86_64" => "calcdate"
      end
    end
  end
end
