# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dsn < Formula
  desc ""
  homepage "https://github.com/sgaunet/homebrew-tools"
  version "2.2.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sgaunet/dsn/releases/download/v2.2.2/dsn_2.2.2_darwin_amd64"
      sha256 "cbc351da5c3df1cc13d64f848fe928790f18a911519cac4a4a07f28adc86a09f"

      def install
        bin.install "dsn_2.2.2_darwin_amd64" => "dsn"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sgaunet/dsn/releases/download/v2.2.2/dsn_2.2.2_darwin_arm64"
      sha256 "a28a2c9c3a3b7336fdb20e21c28ab708842455315cfc99a52c86e95cddacda6c"

      def install
        bin.install "dsn_2.2.2_darwin_arm64" => "dsn"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/sgaunet/dsn/releases/download/v2.2.2/dsn_2.2.2_linux_amd64"
      sha256 "b4d9ad4d11b72624a3a236160b7c1db814673e550e84b582b8bbdf857936deb8"

      def install
        bin.install "dsn_2.2.2_linux_amd64" => "dsn"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sgaunet/dsn/releases/download/v2.2.2/dsn_2.2.2_linux_arm64"
      sha256 "b5a7d1f9ee92a1cb9c0a572fadc25358d772d3ee36a8f11ac544d865408e001d"

      def install
        bin.install "dsn_2.2.2_linux_arm64" => "dsn"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/sgaunet/dsn/releases/download/v2.2.2/dsn_2.2.2_linux_armv6"
      sha256 "3dbc14f3d33000a2c06554d24534ccfc9016e5930107f5419742f5848b4f6327"

      def install
        bin.install "dsn_2.2.2_linux_armv6" => "dsn"
      end
    end
  end
end
