# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Envtemplate < Formula
  desc ""
  homepage "https://github.com/sgaunet/homebrew-tools"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sgaunet/envtemplate/releases/download/v0.1.0/envtemplate_0.1.0_darwin_amd64"
      sha256 "ef1591e77d5b81cf607ad10c9e95ec7a009a2db07dbb28f6916fc7a857ed27c6"

      def install
        bin.install "envtemplate"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sgaunet/envtemplate/releases/download/v0.1.0/envtemplate_0.1.0_darwin_arm64"
      sha256 "2553b2de4eb32f7bd0e1aca18c35dba00b7d4b840cc7342c046b7c7395511efd"

      def install
        bin.install "envtemplate"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sgaunet/envtemplate/releases/download/v0.1.0/envtemplate_0.1.0_linux_arm64"
      sha256 "b8876d7e06a47b133673b60d4915384a9526ff937886b5c4885c8c8414215e7f"

      def install
        bin.install "envtemplate"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sgaunet/envtemplate/releases/download/v0.1.0/envtemplate_0.1.0_linux_amd64"
      sha256 "b1b85fd8e93b18ade5e6793a36b537378de231a8aa085bf6276592cebebca64f"

      def install
        bin.install "envtemplate"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/sgaunet/envtemplate/releases/download/v0.1.0/envtemplate_0.1.0_linux_armv6"
      sha256 "f34b2620202cf8e61dc05da7f43440bcf09af362e914c28663c5f31798f4375f"

      def install
        bin.install "envtemplate"
      end
    end
  end
end
