# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Envtemplate < Formula
  desc ""
  homepage "https://github.com/sgaunet/homebrew-tools"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sgaunet/envtemplate/releases/download/v0.2.1/envtemplate_0.2.1_darwin_amd64"
      sha256 "7c8b01145360f0acc88f22884ca75ac86474a19ae6464a38fc2564b940d264f8"

      def install
        bin.install "envtemplate"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sgaunet/envtemplate/releases/download/v0.2.1/envtemplate_0.2.1_darwin_arm64"
      sha256 "299d209a868757a7d9191636d862ba6df97a4db4c244e1759f07841377c132aa"

      def install
        bin.install "envtemplate"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/sgaunet/envtemplate/releases/download/v0.2.1/envtemplate_0.2.1_linux_armv6"
      sha256 "5ee222458078cab625591a1627315479c67180d127926dcef3b867c03baf59ad"

      def install
        bin.install "envtemplate"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sgaunet/envtemplate/releases/download/v0.2.1/envtemplate_0.2.1_linux_amd64"
      sha256 "318dec87fa383a4d778d0875642e5a937a9ddbd220c338e7e0688845b967d533"

      def install
        bin.install "envtemplate"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sgaunet/envtemplate/releases/download/v0.2.1/envtemplate_0.2.1_linux_arm64"
      sha256 "382e7a7cb17c5387bc0ff772a42a3799d81813c47c456dd8ccec548c5d9d6c24"

      def install
        bin.install "envtemplate"
      end
    end
  end
end
