# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gitcommit < Formula
  desc ""
  homepage "https://github.com/sgaunet/gitcommit"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sgaunet/gitcommit/releases/download/v0.1.0/gitcommit_0.1.0_darwin_amd64"
      sha256 "4a466b5f79fe6422beb51c95167ef977e84c2cf53042473b634dc9228f3190a2"

      def install
        bin.install "gitcommit_0.1.0_darwin_amd64" => "gitcommit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sgaunet/gitcommit/releases/download/v0.1.0/gitcommit_0.1.0_darwin_arm64"
      sha256 "b65836914e4eb33b11d2d62ed350ce33b00323752bf6a011069827c132bd842a"

      def install
        bin.install "gitcommit_0.1.0_darwin_arm64" => "gitcommit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sgaunet/gitcommit/releases/download/v0.1.0/gitcommit_0.1.0_linux_amd64"
      sha256 "76df02e78145fd687a0e367a3c012c87f53130c81abdac0a32e7be93bbfd5fb2"
      def install
        bin.install "gitcommit_0.1.0_linux_amd64" => "gitcommit"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/sgaunet/gitcommit/releases/download/v0.1.0/gitcommit_0.1.0_linux_armv6"
      sha256 "44f14eb0e0fbd55793a32b42b56a75da2b5ee17a90d17fc2bd6004e276869bce"
      def install
        bin.install "gitcommit_0.1.0_linux_armv6" => "gitcommit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sgaunet/gitcommit/releases/download/v0.1.0/gitcommit_0.1.0_linux_arm64"
      sha256 "c63ed639bdafe8e7e353885628c9e7fd5119c4d20a2c438554ee6e815cb5ffc3"
      def install
        bin.install "gitcommit_0.1.0_linux_arm64" => "gitcommit"
      end
    end
  end

  test do
    system "#{bin}/gitcommit", "--help"
  end
end
