# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gitcommit < Formula
  desc ""
  homepage "https://github.com/sgaunet/gitcommit"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sgaunet/gitcommit/releases/download/v0.1.1/gitcommit_0.1.1_darwin_amd64"
      sha256 "fa6d4e406cd0ee1e137bf8f136c8063ea6802238435c81d59c8c0c57ffedef51"

      define_method(:install) do
        bin.install "gitcommit_0.1.1_darwin_amd64" => "gitcommit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sgaunet/gitcommit/releases/download/v0.1.1/gitcommit_0.1.1_darwin_arm64"
      sha256 "4bdf68e1868881e2d65bb902b88c1a0a8b6ae3ca09e536a32e6029c98f084da4"

      define_method(:install) do
        bin.install "gitcommit_0.1.1_darwin_arm64" => "gitcommit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sgaunet/gitcommit/releases/download/v0.1.1/gitcommit_0.1.1_linux_amd64"
      sha256 "83428218d2ef8b9a5b4f1021d437c54a1ac9a2b6677d8c7299ff37577c813369"
      define_method(:install) do
        bin.install "gitcommit_0.1.1_linux_amd64" => "gitcommit"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/sgaunet/gitcommit/releases/download/v0.1.1/gitcommit_0.1.1_linux_armv6"
      sha256 "b86e86cde21dfdb7f77a37f38dd3b0ba4ab9dbfa2ef4c70075ac9d57771eaab1"
      define_method(:install) do
        bin.install "gitcommit_0.1.1_linux_armv6" => "gitcommit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sgaunet/gitcommit/releases/download/v0.1.1/gitcommit_0.1.1_linux_arm64"
      sha256 "c243f1c955ab87b4c2e2d6cbfeb467245afcf29651d0f9819ed9db49a053ffe5"
      define_method(:install) do
        bin.install "gitcommit_0.1.1_linux_arm64" => "gitcommit"
      end
    end
  end

  test do
    system "#{bin}/gitcommit", "--help"
  end
end
