# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitlabMcp < Formula
  desc "A Model Context Protocol (MCP) server that provides GitLab integration tools for Claude Code"
  homepage "https://github.com/sgaunet/gitlab-mcp"
  version "0.4.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sgaunet/gitlab-mcp/releases/download/v0.4.0/gitlab-mcp_0.4.0_darwin_amd64.tar.gz"
      sha256 "f94eb96e3dbfd793cfe388787ee581aa28431627b1bfaa2850ae8bcc5bc4666f"

      def install
        bin.install "gitlab-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sgaunet/gitlab-mcp/releases/download/v0.4.0/gitlab-mcp_0.4.0_darwin_arm64.tar.gz"
      sha256 "d3a6f2d65c38d9cfefc5488107613eab8e68ef0714ae7abd70b792865df22ad2"

      def install
        bin.install "gitlab-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/sgaunet/gitlab-mcp/releases/download/v0.4.0/gitlab-mcp_0.4.0_linux_amd64.tar.gz"
      sha256 "c6128453b829327af07b9250bdec34e8d82ea572f52734e89bf9ac8fe92c9a04"
      def install
        bin.install "gitlab-mcp"
      end
    end
    if Hardware::CPU.arm? and !Hardware::CPU.is_64_bit?
      url "https://github.com/sgaunet/gitlab-mcp/releases/download/v0.4.0/gitlab-mcp_0.4.0_linux_armv6.tar.gz"
      sha256 "5258cbfdc51950fcec08dc008cab8626fcdd3368ae035314a7cc188aee2bda2c"
      def install
        bin.install "gitlab-mcp"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/sgaunet/gitlab-mcp/releases/download/v0.4.0/gitlab-mcp_0.4.0_linux_arm64.tar.gz"
      sha256 "e43e252fd3a68f5fffc7ba57c1bfe0c9d2cbd1ef1f8da2e55bfb6f1e25cc4eb2"
      def install
        bin.install "gitlab-mcp"
      end
    end
  end

  test do
    system "#{bin}/gitlab-mcp", "-h"
  end
end
