# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitlabTokenExpiration < Formula
  desc ""
  homepage "https://github.com/sgaunet/gitlab-token-expiration"
  version "0.4.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sgaunet/gitlab-token-expiration/releases/download/0.4.1/gitlab-token-expiration_0.4.1_darwin_amd64"
      sha256 "c6f51627b75a6ce806142fa0776910ae33b468cdd389e30e41f6f483d4db4bae"

      def install
        bin.install "gitlab-token-expiration_0.4.1_darwin_amd64" => "gitlab-token-expiration"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sgaunet/gitlab-token-expiration/releases/download/0.4.1/gitlab-token-expiration_0.4.1_darwin_arm64"
      sha256 "c94a470a6b46d8970e043e399ada8600f6e2e5c0b165fcb103c35a097df1a226"

      def install
        bin.install "gitlab-token-expiration_0.4.1_darwin_arm64" => "gitlab-token-expiration"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sgaunet/gitlab-token-expiration/releases/download/0.4.1/gitlab-token-expiration_0.4.1_linux_amd64"
      sha256 "bab09451cfb106ef647a0f50b733a29d0319168002764b50268106b5eda1ed6f"
      def install
        bin.install "gitlab-token-expiration_0.4.1_linux_amd64" => "gitlab-token-expiration"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/sgaunet/gitlab-token-expiration/releases/download/0.4.1/gitlab-token-expiration_0.4.1_linux_armv6"
      sha256 "0cf59d2a6804b4d5b0c4f2f7cd6490cd14743dc3cc5d8f6876708bc6a0fa3606"
      def install
        bin.install "gitlab-token-expiration_0.4.1_linux_armv6" => "gitlab-token-expiration"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sgaunet/gitlab-token-expiration/releases/download/0.4.1/gitlab-token-expiration_0.4.1_linux_arm64"
      sha256 "63e74741f70018680ad1c6dd8fc64e6403c8404643985acc3c2bfaf5c57a3245"
      def install
        bin.install "gitlab-token-expiration_0.4.1_linux_arm64" => "gitlab-token-expiration"
      end
    end
  end

  test do
    system "#{bin}/gitlab-token-expiration", "-h"
  end
end
