# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitlabStats < Formula
  desc ""
  homepage "https://github.com/sgaunet/homebrew-tools"
  version "1.0.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/sgaunet/gitlab-stats/releases/download/v1.0.0/gitlab-stats_1.0.0_darwin_arm64"
      sha256 "8911ee93d76773765eab8c9ea8dcf88d110b2cf971d24ee3faceada17c59b3ea"

      def install
        bin.install "gitlab-stats"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sgaunet/gitlab-stats/releases/download/v1.0.0/gitlab-stats_1.0.0_darwin_amd64"
      sha256 "16925b9d94ad455e9d8151013fadc15034b9258a551f8eabb6414066764d240b"

      def install
        bin.install "gitlab-stats"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/sgaunet/gitlab-stats/releases/download/v1.0.0/gitlab-stats_1.0.0_linux_armv6"
      sha256 "642fc7a4edcb6034cd92a6089d275d8f1f5bef8c99e4bea656910d483748ffb1"

      def install
        bin.install "gitlab-stats"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sgaunet/gitlab-stats/releases/download/v1.0.0/gitlab-stats_1.0.0_linux_arm64"
      sha256 "ed20aa9b872602e3b970aee73771cedafbfd99a455811fe59a60b5b4eb8997db"

      def install
        bin.install "gitlab-stats"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sgaunet/gitlab-stats/releases/download/v1.0.0/gitlab-stats_1.0.0_linux_amd64"
      sha256 "dfd9051a17ba55deaa3d152ed7aa6868f54a36712aa24f3da2b630e450e40aa6"

      def install
        bin.install "gitlab-stats"
      end
    end
  end
end
