# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitlabTokenExpiration < Formula
  desc ""
  homepage "https://github.com/sgaunet/gitlab-token-expiration"
  version "0.3.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sgaunet/gitlab-token-expiration/releases/download/0.3.1/gitlab-token-expiration_0.3.1_darwin_amd64"
      sha256 "df7f47aa3195c164e4b4c29ff423e62481f2e835eb9a558a20adb17364e1192a"

      def install
        bin.install "gitlab-token-expiration_0.3.1_darwin_amd64" => "gitlab-token-expiration"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sgaunet/gitlab-token-expiration/releases/download/0.3.1/gitlab-token-expiration_0.3.1_darwin_arm64"
      sha256 "82134783103f4bc1ae0a1991215117cc0e2ab8d1fc724d9c623b3dcc829a37e3"

      def install
        bin.install "gitlab-token-expiration_0.3.1_darwin_arm64" => "gitlab-token-expiration"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/sgaunet/gitlab-token-expiration/releases/download/0.3.1/gitlab-token-expiration_0.3.1_linux_amd64"
      sha256 "c07bdfa76267bfeda011348ead2ddfc26f4e832e243a0a3b7f21eaf832a4fcd4"
      def install
        bin.install "gitlab-token-expiration_0.3.1_linux_amd64" => "gitlab-token-expiration"
      end
    end
    if Hardware::CPU.arm? and !Hardware::CPU.is_64_bit?
      url "https://github.com/sgaunet/gitlab-token-expiration/releases/download/0.3.1/gitlab-token-expiration_0.3.1_linux_armv6"
      sha256 "a71bb238b508cb48853df5991efae2e628387ec95a6f648e2b92f1fa09ddb04e"
      def install
        bin.install "gitlab-token-expiration_0.3.1_linux_armv6" => "gitlab-token-expiration"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/sgaunet/gitlab-token-expiration/releases/download/0.3.1/gitlab-token-expiration_0.3.1_linux_arm64"
      sha256 "1e3198007465b032187551d3e6feb36d4730a04756e8d74f4490a3df1279b3d2"
      def install
        bin.install "gitlab-token-expiration_0.3.1_linux_arm64" => "gitlab-token-expiration"
      end
    end
  end

  test do
    system "#{bin}/gitlab-token-expiration", "-h"
  end
end
