# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitlabMcp < Formula
  desc "A Model Context Protocol (MCP) server that provides GitLab integration tools for Claude Code"
  homepage "https://github.com/sgaunet/gitlab-mcp"
  version "0.10.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sgaunet/gitlab-mcp/releases/download/v0.10.1/gitlab-mcp_0.10.1_darwin_amd64.tar.gz"
      sha256 "90a86e6e5dbd7f0737d17775722c49f5568c665bc0ba3ea1544e790a559db190"

      def install
        bin.install "gitlab-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sgaunet/gitlab-mcp/releases/download/v0.10.1/gitlab-mcp_0.10.1_darwin_arm64.tar.gz"
      sha256 "5f78c3170319b1dcc557f76fc793de1a586c3fe57024d942a3d9f68fab593f3a"

      def install
        bin.install "gitlab-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sgaunet/gitlab-mcp/releases/download/v0.10.1/gitlab-mcp_0.10.1_linux_amd64.tar.gz"
      sha256 "8de64f845b7f67aa50d806a8bea56bf6ae15ee9f3c7628a8679cfac11ad6cdbd"
      def install
        bin.install "gitlab-mcp"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/sgaunet/gitlab-mcp/releases/download/v0.10.1/gitlab-mcp_0.10.1_linux_armv6.tar.gz"
      sha256 "bf97ea3192aa4302e037aa4d346807d1e6cd166a802472a1b6f92eedc0320162"
      def install
        bin.install "gitlab-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sgaunet/gitlab-mcp/releases/download/v0.10.1/gitlab-mcp_0.10.1_linux_arm64.tar.gz"
      sha256 "0449e458bb50ada039745348e9fcbed986c375750ffece3caf90290062c82f46"
      def install
        bin.install "gitlab-mcp"
      end
    end
  end

  test do
    system "#{bin}/gitlab-mcp", "-h"
  end
end
