# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitlabBackup < Formula
  desc "A tool for backing up GitLab projects"
  homepage "https://github.com/sgaunet/gitlab-backup"
  version "1.12.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sgaunet/gitlab-backup/releases/download/v1.12.1/gitlab-backup_1.12.1_darwin_amd64"
      sha256 "1be87df21bc4618d5a6853328ac70867c3e81561e9b779f36c5d8032e2047657"

      def install
        bin.install "gitlab-backup"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sgaunet/gitlab-backup/releases/download/v1.12.1/gitlab-backup_1.12.1_darwin_arm64"
      sha256 "0cd1fc8c12732ebd30bea625ffe7b20edf2228b8ea5fe5e7e48ad58433148f3b"

      def install
        bin.install "gitlab-backup"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/sgaunet/gitlab-backup/releases/download/v1.12.1/gitlab-backup_1.12.1_linux_amd64"
      sha256 "7a9bb251c6838d0e15e58f1db1baaf86bcc72351729f39b2997f31199e59f4d2"
      def install
        bin.install "gitlab-backup"
      end
    end
    if Hardware::CPU.arm? and !Hardware::CPU.is_64_bit?
      url "https://github.com/sgaunet/gitlab-backup/releases/download/v1.12.1/gitlab-backup_1.12.1_linux_armv6"
      sha256 "e85d6ea3ebc44e78823f0ea7176cbd9575c37d3caf83310f4316c5cb980f7bb8"
      def install
        bin.install "gitlab-backup"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/sgaunet/gitlab-backup/releases/download/v1.12.1/gitlab-backup_1.12.1_linux_arm64"
      sha256 "366cb77b5e14057a4db9918a5e488560fbce59469a54af6ff1871eaf7143fd59"
      def install
        bin.install "gitlab-backup"
      end
    end
  end

  test do
    system "#{bin}/gitlab-backup", "--help"
  end
end
