# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitlabStats < Formula
  desc ""
  homepage "https://github.com/sgaunet/homebrew-tools"
  version "0.1.0"
  depends_on :linux

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/sgaunet/gitlab-stats/releases/download/v0.1.0/gitlab-stats_0.1.0_linux_armv6"
      sha256 "cb6dcf5baff5de7d4f337e9a36a34983519204fc440d101082302f04b59b2771"

      def install
        bin.install "gitlab-stats_0.1.0_linux_armv6" => "gitlab-stats"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sgaunet/gitlab-stats/releases/download/v0.1.0/gitlab-stats_0.1.0_linux_amd64"
      sha256 "02ddd24b688936bd4d39afbbc5027e3888baea8baba876d754aeab109bf1eb1b"

      def install
        bin.install "gitlab-stats_0.1.0_linux_amd64" => "gitlab-stats"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sgaunet/gitlab-stats/releases/download/v0.1.0/gitlab-stats_0.1.0_linux_arm64"
      sha256 "568921b6d9a13fe552699629e7c9aed1d29c61029abb0d1bb18068c319532909"

      def install
        bin.install "gitlab-stats_0.1.0_linux_arm64" => "gitlab-stats"
      end
    end
  end
end
