# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gocrypt < Formula
  desc ""
  homepage "https://github.com/sgaunet/homebrew-tools"
  version "1.3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sgaunet/gocrypt/releases/download/v1.3.0/gocrypt_1.3.0_darwin_amd64"
      sha256 "0abdf3091557f69e694f1939f86e7c7c395a11e686d9c61a084ba6f8848601fc"

      def install
        bin.install "gocrypt"
        # bash_completion.install "completions/foo.bash" => "foo"
        # ...
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sgaunet/gocrypt/releases/download/v1.3.0/gocrypt_1.3.0_darwin_arm64"
      sha256 "5b9bfe71885d267576831745f1df098536ef567d42270d93913454f70e00c201"

      def install
        bin.install "gocrypt"
        # bash_completion.install "completions/foo.bash" => "foo"
        # ...
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sgaunet/gocrypt/releases/download/v1.3.0/gocrypt_1.3.0_linux_arm64"
      sha256 "b11171de9c206a695c8ef3c85e0bffcf4225a49491298fafdac4257b7f0d5a9a"

      def install
        bin.install "gocrypt"
        # bash_completion.install "completions/foo.bash" => "foo"
        # ...
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/sgaunet/gocrypt/releases/download/v1.3.0/gocrypt_1.3.0_linux_armv6"
      sha256 "a0efbb8bbda7ef0f864838b7a582c147bdfed18276ebd1382507a2b8a8461d90"

      def install
        bin.install "gocrypt"
        # bash_completion.install "completions/foo.bash" => "foo"
        # ...
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sgaunet/gocrypt/releases/download/v1.3.0/gocrypt_1.3.0_linux_amd64"
      sha256 "e2b7a60b0fb0471e5570594255234d3cff1e18f1a1f74dde38145054ed7e7568"

      def install
        bin.install "gocrypt"
        # bash_completion.install "completions/foo.bash" => "foo"
        # ...
      end
    end
  end
end
