# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HelmchartHelper < Formula
  desc ""
  homepage "https://github.com/sgaunet/homebrew-tools"
  version "0.1.0-beta5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sgaunet/helmchart-helper/releases/download/v0.1.0-beta5/helmchart-helper_0.1.0-beta5_darwin_amd64"
      sha256 "9b0dd8c1826394631e01a017a2dfb7a10abb6a905e5c319580371d61f83c5546"

      def install
        bin.install "helmchart-helper"
        # bash_completion.install "completions/foo.bash" => "foo"
        # ...
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sgaunet/helmchart-helper/releases/download/v0.1.0-beta5/helmchart-helper_0.1.0-beta5_darwin_arm64"
      sha256 "12ec1d3ce833baf9663f35996818db1c52a412fb03e43f4ab3ff0c1fd78befe5"

      def install
        bin.install "helmchart-helper"
        # bash_completion.install "completions/foo.bash" => "foo"
        # ...
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/sgaunet/helmchart-helper/releases/download/v0.1.0-beta5/helmchart-helper_0.1.0-beta5_linux_amd64"
      sha256 "572acf2229918eee5e936a5fd3eefd4052a6f5e2a49580af960e64efe758615a"

      def install
        bin.install "helmchart-helper"
        # bash_completion.install "completions/foo.bash" => "foo"
        # ...
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sgaunet/helmchart-helper/releases/download/v0.1.0-beta5/helmchart-helper_0.1.0-beta5_linux_arm64"
      sha256 "be871a83e5c9db5993e42477114ab354c4e50a0370e5a8c5cb0a9a892974fb86"

      def install
        bin.install "helmchart-helper"
        # bash_completion.install "completions/foo.bash" => "foo"
        # ...
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/sgaunet/helmchart-helper/releases/download/v0.1.0-beta5/helmchart-helper_0.1.0-beta5_linux_armv6"
      sha256 "e726ad44f7d430974f271e2a09cd51add63fbb39996df43f5231c79edc407605"

      def install
        bin.install "helmchart-helper"
        # bash_completion.install "completions/foo.bash" => "foo"
        # ...
      end
    end
  end
end
