# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class JwtCli < Formula
  desc ""
  homepage "https://github.com/sgaunet/jwt-cli"
  version "1.2.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sgaunet/jwt-cli/releases/download/v1.2.5/jwt-cli_1.2.5_darwin_amd64"
      sha256 "8323134a6d73d00549763d5c919996d0b501be97a02cbfe8f6f7f74e0d30f0fe"

      def install
        bin.install "jwt-cli_1.2.5_darwin_amd64" => "jwt-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sgaunet/jwt-cli/releases/download/v1.2.5/jwt-cli_1.2.5_darwin_arm64"
      sha256 "3406af0dc043fe95e810bd3f80d99e5f3496bf2218c5b3c1736b288d9b644e81"

      def install
        bin.install "jwt-cli_1.2.5_darwin_arm64" => "jwt-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/sgaunet/jwt-cli/releases/download/v1.2.5/jwt-cli_1.2.5_linux_amd64"
      sha256 "ed72db9fcd6c4e25950ff5bbcba4c2233cb797f5c68f6cf0a0b6b783a1dbafd2"
      def install
        bin.install "jwt-cli_1.2.5_linux_amd64" => "jwt-cli"
      end
    end
    if Hardware::CPU.arm? and !Hardware::CPU.is_64_bit?
      url "https://github.com/sgaunet/jwt-cli/releases/download/v1.2.5/jwt-cli_1.2.5_linux_armv6"
      sha256 "9eebf3216086969184f00de2cef241af505421f8fddc0ab8de11165903578463"
      def install
        bin.install "jwt-cli_1.2.5_linux_armv6" => "jwt-cli"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/sgaunet/jwt-cli/releases/download/v1.2.5/jwt-cli_1.2.5_linux_arm64"
      sha256 "2c2cf8b23b16c9d1d9199b4c7519ba80cc836f7d0123c6cc8536030eb2c78ff2"
      def install
        bin.install "jwt-cli_1.2.5_linux_arm64" => "jwt-cli"
      end
    end
  end

  test do
    system "#{bin}/jwt-cli", "--help"
  end
end
