# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Logwrap < Formula
  desc ""
  homepage "https://github.com/sgaunet/logwrap"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sgaunet/logwrap/releases/download/v0.1.0/logwrap_0.1.0_darwin_amd64"
      sha256 "8046a4b49a064b51debc204fa2cf680ac25befa3d36b505549afdb7d9340b071"

      def install
        bin.install "logwrap_0.1.0_darwin_amd64" => "logwrap"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sgaunet/logwrap/releases/download/v0.1.0/logwrap_0.1.0_darwin_arm64"
      sha256 "dcfe44e3852943bc86b9083a1fdacd6ab3c520f7f4c742988b6bd14d305e04e3"

      def install
        bin.install "logwrap_0.1.0_darwin_arm64" => "logwrap"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sgaunet/logwrap/releases/download/v0.1.0/logwrap_0.1.0_linux_amd64"
      sha256 "1220d90542f7fbe70dfc009d9b9309a662fce97a76456915ecc2ff53edcd9a08"
      def install
        bin.install "logwrap_0.1.0_linux_amd64" => "logwrap"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/sgaunet/logwrap/releases/download/v0.1.0/logwrap_0.1.0_linux_armv6"
      sha256 "8d77e1ab37a36727b6173198f543ea36662e16c6f07bb438711a7ca94361cc5b"
      def install
        bin.install "logwrap_0.1.0_linux_armv6" => "logwrap"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sgaunet/logwrap/releases/download/v0.1.0/logwrap_0.1.0_linux_arm64"
      sha256 "c83af0d900a7f2c99e40f2955b81553ac48c78553ff8bb68e21c9d9d7b903cc9"
      def install
        bin.install "logwrap_0.1.0_linux_arm64" => "logwrap"
      end
    end
  end

  test do
    system "#{bin}/logwrap", "-h"
  end
end
