# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Logwrap < Formula
  desc ""
  homepage "https://github.com/sgaunet/logwrap"
  version "0.3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sgaunet/logwrap/releases/download/v0.3.0/logwrap_0.3.0_darwin_amd64"
      sha256 "7e86d9fa664496e43350ddb957b045eb5ddb1c76ad155d624c28179c213b2902"

      define_method(:install) do
        bin.install "logwrap_0.3.0_darwin_amd64" => "logwrap"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sgaunet/logwrap/releases/download/v0.3.0/logwrap_0.3.0_darwin_arm64"
      sha256 "0366d4cb118911a04b1649056773eff705c1555f31b6b061e7c55d9f38d4ee66"

      define_method(:install) do
        bin.install "logwrap_0.3.0_darwin_arm64" => "logwrap"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sgaunet/logwrap/releases/download/v0.3.0/logwrap_0.3.0_linux_amd64"
      sha256 "429646e9db097cdb2bbd5e59229c159dbb50fc2521a156e37d3435865408bd55"
      define_method(:install) do
        bin.install "logwrap_0.3.0_linux_amd64" => "logwrap"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/sgaunet/logwrap/releases/download/v0.3.0/logwrap_0.3.0_linux_armv6"
      sha256 "db25e5ee090b62225c938371b1646cd248c1dc68a2d435d82513a0dd7eaea954"
      define_method(:install) do
        bin.install "logwrap_0.3.0_linux_armv6" => "logwrap"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sgaunet/logwrap/releases/download/v0.3.0/logwrap_0.3.0_linux_arm64"
      sha256 "d48c8a5f11cdd2f8c4a4331f15f2211829e1d9fa331e2659dbe0c26649e3e877"
      define_method(:install) do
        bin.install "logwrap_0.3.0_linux_arm64" => "logwrap"
      end
    end
  end

  test do
    system "#{bin}/logwrap", "-h"
  end
end
