# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Logwrap < Formula
  desc ""
  homepage "https://github.com/sgaunet/logwrap"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sgaunet/logwrap/releases/download/v0.2.0/logwrap_0.2.0_darwin_amd64"
      sha256 "c075cbb8fd054d5324e2440b995be0569b3e2663b68a787f9fd0380e69912a25"

      def install
        bin.install "logwrap_0.2.0_darwin_amd64" => "logwrap"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sgaunet/logwrap/releases/download/v0.2.0/logwrap_0.2.0_darwin_arm64"
      sha256 "0822d695df3dfcf31eccc360d6cb2e04b31f7ac866e61604c08aa13a6b3366f8"

      def install
        bin.install "logwrap_0.2.0_darwin_arm64" => "logwrap"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sgaunet/logwrap/releases/download/v0.2.0/logwrap_0.2.0_linux_amd64"
      sha256 "70544b4a4a902d771b11e18e697e344719e296ea090501ecd976c1b0d7a9ad4d"
      def install
        bin.install "logwrap_0.2.0_linux_amd64" => "logwrap"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/sgaunet/logwrap/releases/download/v0.2.0/logwrap_0.2.0_linux_armv6"
      sha256 "c040a2af07e00ff70357491a8bdba3a65c3b962f140a54ee9a58ca0c67093150"
      def install
        bin.install "logwrap_0.2.0_linux_armv6" => "logwrap"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sgaunet/logwrap/releases/download/v0.2.0/logwrap_0.2.0_linux_arm64"
      sha256 "706b77f5d4f239b2e9965f8dc9b22c0fc4cd817274b909e66579bb6b23e18019"
      def install
        bin.install "logwrap_0.2.0_linux_arm64" => "logwrap"
      end
    end
  end

  test do
    system "#{bin}/logwrap", "-h"
  end
end
