# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mdtohtml < Formula
  desc "A simple and efficient Markdown to HTML converter"
  homepage "https://github.com/sgaunet/mdtohtml"
  version "1.1.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sgaunet/mdtohtml/releases/download/v1.1.4/mdtohtml_1.1.4_darwin_amd64.tar.gz"
      sha256 "fb689ceaacefe599511f2fb3b9bdfca74a328051bb66c867709ef481ff97f64e"

      def install
        bin.install "mdtohtml"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sgaunet/mdtohtml/releases/download/v1.1.4/mdtohtml_1.1.4_darwin_arm64.tar.gz"
      sha256 "b780b61467f8ed63a53b86563f46ddd6a16ade578aeac8edd19011986a3729bb"

      def install
        bin.install "mdtohtml"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/sgaunet/mdtohtml/releases/download/v1.1.4/mdtohtml_1.1.4_linux_amd64.tar.gz"
      sha256 "61e79b8de45ec09dfad57291149186bb805ac1ecac99337fabc3fc9ebe35c736"
      def install
        bin.install "mdtohtml"
      end
    end
    if Hardware::CPU.arm? and !Hardware::CPU.is_64_bit?
      url "https://github.com/sgaunet/mdtohtml/releases/download/v1.1.4/mdtohtml_1.1.4_linux_armv6.tar.gz"
      sha256 "534677f91d194423e4895e23858d7ca6b5554ff87cdc90dc81af173cdb6ffa46"
      def install
        bin.install "mdtohtml"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/sgaunet/mdtohtml/releases/download/v1.1.4/mdtohtml_1.1.4_linux_arm64.tar.gz"
      sha256 "81213f8ad390e0d856722d6bc8dbb388dc1201c45d254d520b8c31c119702eae"
      def install
        bin.install "mdtohtml"
      end
    end
  end

  test do
    system "#{bin}/mdtohtml", "--help"
  end
end
