# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Moraine < Formula
  desc "A tool for [describe your project]"
  homepage "https://github.com/sgaunet/moraine"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sgaunet/moraine/releases/download/v0.1.1/moraine_0.1.1_darwin_amd64"
      sha256 "b90663fef949397197a256d34539105afd6fbc937b17cf1d2441c88da4ddd821"

      define_method(:install) do
        bin.install "moraine_0.1.1_darwin_amd64" => "moraine"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sgaunet/moraine/releases/download/v0.1.1/moraine_0.1.1_darwin_arm64"
      sha256 "d13dcc811835fb29155957605c99253a2873b952448cdf1eb16dabb9a1a77e5d"

      define_method(:install) do
        bin.install "moraine_0.1.1_darwin_arm64" => "moraine"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sgaunet/moraine/releases/download/v0.1.1/moraine_0.1.1_linux_amd64"
      sha256 "fea3bc5d040d6609f34b0aa7dc720f1dc2d097b187f7e57881a7af2ae8c8eca6"
      define_method(:install) do
        bin.install "moraine_0.1.1_linux_amd64" => "moraine"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sgaunet/moraine/releases/download/v0.1.1/moraine_0.1.1_linux_arm64"
      sha256 "a6a59406a5a88fb6ea19df57d5f3ee49a0dd9c1818de6e3c967da10756a0b8df"
      define_method(:install) do
        bin.install "moraine_0.1.1_linux_arm64" => "moraine"
      end
    end
  end

  test do
    system "#{bin}/moraine", "--help"
  end
end
