# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PostgresqlMcp < Formula
  desc "A Model Context Protocol (MCP) server that provides Postgresql integration tools for MCP clients."
  homepage "https://github.com/sgaunet/postgresql-mcp"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sgaunet/postgresql-mcp/releases/download/0.1.0/postgresql-mcp_0.1.0_darwin_amd64.tar.gz"
      sha256 "5ccd8214b1c02c91f82a69f45c3c4d1d7e001b1cda93e5d86142ce1bb56fb9eb"

      def install
        bin.install "postgresql-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sgaunet/postgresql-mcp/releases/download/0.1.0/postgresql-mcp_0.1.0_darwin_arm64.tar.gz"
      sha256 "232496077c5cdb3634b41ee7a3d21fa35e3336e3d878cb5b62796380129f8e8b"

      def install
        bin.install "postgresql-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sgaunet/postgresql-mcp/releases/download/0.1.0/postgresql-mcp_0.1.0_linux_amd64.tar.gz"
      sha256 "38656d6381e7815bfd93c5f245c419a0b1d5e6391aaca5dd3e1d58c6391c8892"
      def install
        bin.install "postgresql-mcp"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/sgaunet/postgresql-mcp/releases/download/0.1.0/postgresql-mcp_0.1.0_linux_armv6.tar.gz"
      sha256 "6bd02a7a8fe81003443277398c2ab58a86deb74394b23d303d6cbfe8b320d74e"
      def install
        bin.install "postgresql-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sgaunet/postgresql-mcp/releases/download/0.1.0/postgresql-mcp_0.1.0_linux_arm64.tar.gz"
      sha256 "c7b08873964193551b2db22b54df8a9b802a28e7edfb0e9a7eb39f913c6236a2"
      def install
        bin.install "postgresql-mcp"
      end
    end
  end

  test do
    system "#{bin}/postgresql-mcp", "-h"
  end
end
