# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PostgresqlMcp < Formula
  desc "A Model Context Protocol (MCP) server that provides Postgresql integration tools for MCP clients."
  homepage "https://github.com/sgaunet/postgresql-mcp"
  version "0.1.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sgaunet/postgresql-mcp/releases/download/v0.1.2/postgresql-mcp_0.1.2_darwin_amd64.tar.gz"
      sha256 "ab448cde88fe3cb03ca0d51272f72e74a2c82770487a328b72af5c8cb952fc59"

      def install
        bin.install "postgresql-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sgaunet/postgresql-mcp/releases/download/v0.1.2/postgresql-mcp_0.1.2_darwin_arm64.tar.gz"
      sha256 "8d253352e1078db71dd585eb946070a13ac6ffa23097297bb6c73bd1a2650070"

      def install
        bin.install "postgresql-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sgaunet/postgresql-mcp/releases/download/v0.1.2/postgresql-mcp_0.1.2_linux_amd64.tar.gz"
      sha256 "b515b2ef343c689b3291c245f782110960f6b3ec35ef5342e19d212260bdeeb6"
      def install
        bin.install "postgresql-mcp"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/sgaunet/postgresql-mcp/releases/download/v0.1.2/postgresql-mcp_0.1.2_linux_armv6.tar.gz"
      sha256 "95f938cb52f8da61c4af48a3b8d72c244a0385b321e3e82a1289f2f9281fbb74"
      def install
        bin.install "postgresql-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sgaunet/postgresql-mcp/releases/download/v0.1.2/postgresql-mcp_0.1.2_linux_arm64.tar.gz"
      sha256 "091062d6e7a475bf4de4aa49928e6aba80f57cdf6e46c62f9f25d0f6af84081b"
      def install
        bin.install "postgresql-mcp"
      end
    end
  end

  test do
    system "#{bin}/postgresql-mcp", "-h"
  end
end
