# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pplx < Formula
  desc ""
  homepage "https://github.com/sgaunet/homebrew-tools"
  version "0.1.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sgaunet/pplx/releases/download/v0.1.2/pplx_0.1.2_darwin_amd64"
      sha256 "e8bc2b5a12f1b27c8c76bf2839abf5100150371bd798c5ed7ce20a708096c059"

      def install
        bin.install "pplx_0.1.2_darwin_amd64" => "pplx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sgaunet/pplx/releases/download/v0.1.2/pplx_0.1.2_darwin_arm64"
      sha256 "cb792527262e087ec10b008a5282c88ce03625c061369bb5a83b807a63608326"

      def install
        bin.install "pplx_0.1.2_darwin_arm64" => "pplx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sgaunet/pplx/releases/download/v0.1.2/pplx_0.1.2_linux_amd64"
        sha256 "e35d183161999d2d6ce98d9284074159d294f888d54c07f9a45aca4ee3de0726"

        def install
          bin.install "pplx_0.1.2_linux_amd64" => "pplx"
        end
      end
    end
    if Hardware::CPU.arm?
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/sgaunet/pplx/releases/download/v0.1.2/pplx_0.1.2_linux_armv6"
        sha256 "0a3a6256b0a1b15bc05e8f4bd935c04aeb27b20c5b1c76203ede8c9f7ee7b352"

        def install
          bin.install "pplx_0.1.2_linux_armv6" => "pplx"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sgaunet/pplx/releases/download/v0.1.2/pplx_0.1.2_linux_arm64"
        sha256 "7bb9d4644eaa2369553c2ac355e96d42e1ec0849f751f8fd95246278fe40589d"

        def install
          bin.install "pplx_0.1.2_linux_arm64" => "pplx"
        end
      end
    end
  end
end
