# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pplx < Formula
  desc ""
  homepage "https://github.com/sgaunet/pplx"
  version "0.11.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sgaunet/pplx/releases/download/v0.11.0/pplx_0.11.0_darwin_amd64"
      sha256 "9ae65d60f09be42e7da6e3ab100b4a14326b925b12c911f0aeade9f904441b3e"

      define_method(:install) do
        bin.install "pplx_0.11.0_darwin_amd64" => "pplx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sgaunet/pplx/releases/download/v0.11.0/pplx_0.11.0_darwin_arm64"
      sha256 "4250fa273a10e7a1352b470804b274746a5ee24b76bb7c5c91b0690d964022ab"

      define_method(:install) do
        bin.install "pplx_0.11.0_darwin_arm64" => "pplx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sgaunet/pplx/releases/download/v0.11.0/pplx_0.11.0_linux_amd64"
      sha256 "d63e42f679371b01cb00e3534d18e1d9b51553787f54c7de12d29e9e0cf7b45d"
      define_method(:install) do
        bin.install "pplx_0.11.0_linux_amd64" => "pplx"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/sgaunet/pplx/releases/download/v0.11.0/pplx_0.11.0_linux_armv6"
      sha256 "0e32f5e8dc4a456afb52f0268dbda9d205778cee2564cd73705a717bc60b31ce"
      define_method(:install) do
        bin.install "pplx_0.11.0_linux_armv6" => "pplx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sgaunet/pplx/releases/download/v0.11.0/pplx_0.11.0_linux_arm64"
      sha256 "52c8dcdde860154498eef49894d56830748d1867bd396b0b51d1fbf13729f4c9"
      define_method(:install) do
        bin.install "pplx_0.11.0_linux_arm64" => "pplx"
      end
    end
  end

  test do
    system "#{bin}/pplx", "--help"
  end
end
