# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pplx < Formula
  desc ""
  homepage "https://github.com/sgaunet/pplx"
  version "0.9.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sgaunet/pplx/releases/download/v0.9.0/pplx_0.9.0_darwin_amd64"
      sha256 "4c8d85c1c1da9c28ef1f85ceb9300a32d9ce015d1983ce482816d915a9b11026"

      define_method(:install) do
        bin.install "pplx_0.9.0_darwin_amd64" => "pplx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sgaunet/pplx/releases/download/v0.9.0/pplx_0.9.0_darwin_arm64"
      sha256 "c0e87fa5827ef7d0de95b677cf66f0f7835d4074f389d762b8321e7b0c42db1d"

      define_method(:install) do
        bin.install "pplx_0.9.0_darwin_arm64" => "pplx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sgaunet/pplx/releases/download/v0.9.0/pplx_0.9.0_linux_amd64"
      sha256 "8ae5a7a8f756ba2681284bcb7aac7d15a40c933c5f19b482a62420b6f5e73c94"
      define_method(:install) do
        bin.install "pplx_0.9.0_linux_amd64" => "pplx"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/sgaunet/pplx/releases/download/v0.9.0/pplx_0.9.0_linux_armv6"
      sha256 "1dd0be9e17b99ee50a4b83c124b611fe9146e81d063c11e8b8113c15c7addfa2"
      define_method(:install) do
        bin.install "pplx_0.9.0_linux_armv6" => "pplx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sgaunet/pplx/releases/download/v0.9.0/pplx_0.9.0_linux_arm64"
      sha256 "07139a66aee4316fb6b257b2da0b02c00c8445005253f54644e4ad8c9e12be22"
      define_method(:install) do
        bin.install "pplx_0.9.0_linux_arm64" => "pplx"
      end
    end
  end

  test do
    system "#{bin}/pplx", "--help"
  end
end
