# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ResticAgeKey < Formula
  desc "A tool for [describe your project]"
  homepage "https://github.com/sgaunet/restic-age-key"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sgaunet/restic-age-key/releases/download/v0.1.0/restic-age-key_0.1.0_darwin_amd64"
      sha256 "ee3ea3128d542f05229912166f130749289b368d3ba5115028ae5ba0e6643464"

      define_method(:install) do
        bin.install "restic-age-key_0.1.0_darwin_amd64" => "restic-age-key"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sgaunet/restic-age-key/releases/download/v0.1.0/restic-age-key_0.1.0_darwin_arm64"
      sha256 "26d0d8b12753c80425a254696a03eb2dc8881615291f640a2cb02bb28c9f758c"

      define_method(:install) do
        bin.install "restic-age-key_0.1.0_darwin_arm64" => "restic-age-key"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sgaunet/restic-age-key/releases/download/v0.1.0/restic-age-key_0.1.0_linux_amd64"
      sha256 "72c313a419da9119f4418b0890604e256a6103cbd4c3baa91b3ee0245d744f0e"
      define_method(:install) do
        bin.install "restic-age-key_0.1.0_linux_amd64" => "restic-age-key"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/sgaunet/restic-age-key/releases/download/v0.1.0/restic-age-key_0.1.0_linux_armv6"
      sha256 "5195187b1acb74143a0f1cabac328cf7ea4bc3431983278ba69caa41db9474ff"
      define_method(:install) do
        bin.install "restic-age-key_0.1.0_linux_armv6" => "restic-age-key"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sgaunet/restic-age-key/releases/download/v0.1.0/restic-age-key_0.1.0_linux_arm64"
      sha256 "9ffbc90af741a05fec97518f823c08b61398d6d1c7423be14a61800f65447ca9"
      define_method(:install) do
        bin.install "restic-age-key_0.1.0_linux_arm64" => "restic-age-key"
      end
    end
  end

  test do
    system "#{bin}/restic-age-key", "--help"
  end
end
