# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wms < Formula
  desc ""
  homepage "https://github.com/sgaunet/wms"
  version "0.5.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sgaunet/wms/releases/download/v0.5.0/wms_0.5.0_darwin_amd64"
      sha256 "918c98b364b8f2d03dd09127888b13116bba5f7e45b301d33131d9c3eaadb217"

      def install
        bin.install "wms_0.5.0_darwin_amd64" => "wms"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sgaunet/wms/releases/download/v0.5.0/wms_0.5.0_darwin_arm64"
      sha256 "843b808649cb76a0232a1961bc4a268feedb9bfc01c039c74f0caa7ea8114038"

      def install
        bin.install "wms_0.5.0_darwin_arm64" => "wms"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sgaunet/wms/releases/download/v0.5.0/wms_0.5.0_linux_amd64"
      sha256 "af5631b9f5a34637b56aa23b5937a08563b26732459fc076e493203be62e73c6"
      def install
        bin.install "wms_0.5.0_linux_amd64" => "wms"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/sgaunet/wms/releases/download/v0.5.0/wms_0.5.0_linux_armv6"
      sha256 "020285c390b73b296840dd35759719324dc50d76a9b709972fbe4882318ca168"
      def install
        bin.install "wms_0.5.0_linux_armv6" => "wms"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sgaunet/wms/releases/download/v0.5.0/wms_0.5.0_linux_arm64"
      sha256 "edac8d8c3308d6f745d277f34a9d77b34ba9b9d71cca00b5331187b4cd57bddd"
      def install
        bin.install "wms_0.5.0_linux_arm64" => "wms"
      end
    end
  end

  test do
    system "#{bin}/wms", "--help"
  end
end
