# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wms < Formula
  desc ""
  homepage "https://github.com/sgaunet/homebrew-tools"
  version "0.3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sgaunet/wms/releases/download/v0.3.0/wms_0.3.0_darwin_amd64"
      sha256 "bf6dc846635341fc763eb20a9edec7eab4e1f15c1977b6cb7fb46bd62762cabf"

      def install
        bin.install "wms_0.3.0_darwin_amd64" => "wms"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sgaunet/wms/releases/download/v0.3.0/wms_0.3.0_darwin_arm64"
      sha256 "e644af27820c54c63274180d1a99ee5436a9433669e85c910bb6cdc07238e9d0"

      def install
        bin.install "wms_0.3.0_darwin_arm64" => "wms"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sgaunet/wms/releases/download/v0.3.0/wms_0.3.0_linux_amd64"
        sha256 "45b6907ab57179d243712070628f8400e57fbe7aaf6efcedda008a2ccf42e9f1"

        def install
          bin.install "wms_0.3.0_linux_amd64" => "wms"
        end
      end
    end
    if Hardware::CPU.arm?
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/sgaunet/wms/releases/download/v0.3.0/wms_0.3.0_linux_armv6"
        sha256 "5fc7c70a426019ff60f5d98ff14a2ab3787d36037de407575753681a9d5fc2bd"

        def install
          bin.install "wms_0.3.0_linux_armv6" => "wms"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sgaunet/wms/releases/download/v0.3.0/wms_0.3.0_linux_arm64"
        sha256 "31bb386d74cefc5c4a20b39dd6b1ce7c9d255fab07a7100ab5606f9bf539a84b"

        def install
          bin.install "wms_0.3.0_linux_arm64" => "wms"
        end
      end
    end
  end
end
